// Mocks generated by Mockito 5.4.6 from annotations
// in npt_flutter/test/features/settings/bloc/settings_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:at_client/at_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:npt_flutter/features/settings/settings.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAtKey_0 extends _i1.SmartFake implements _i2.AtKey {
  _FakeAtKey_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettings_1 extends _i1.SmartFake implements _i3.Settings {
  _FakeSettings_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i3.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AtKey get settingsAtKey =>
      (super.noSuchMethod(
            Invocation.getter(#settingsAtKey),
            returnValue: _FakeAtKey_0(this, Invocation.getter(#settingsAtKey)),
          )
          as _i2.AtKey);

  @override
  _i3.Settings get defaultSettings =>
      (super.noSuchMethod(
            Invocation.getter(#defaultSettings),
            returnValue: _FakeSettings_1(
              this,
              Invocation.getter(#defaultSettings),
            ),
          )
          as _i3.Settings);

  @override
  _i4.Future<_i3.Settings?> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue: _i4.Future<_i3.Settings?>.value(),
          )
          as _i4.Future<_i3.Settings?>);

  @override
  _i4.Future<bool> putSettings(_i3.Settings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#putSettings, [settings]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteSettings(_i3.Settings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSettings, [settings]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
