version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directories:
      - "/packages/c/sshnpd/tools/"
      - "/packages/dart/sshnoports/tools/"
      - "/tests/e2e_all/dockerfiles/"
      - "/tests/end2end_tests/image/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
      exclude:
      - "atsigncompany/*"
    groups:
      docker:
        patterns:
          - "*"
  - package-ecosystem: "pub"
    directories:
      - "/packages/dart/sshnoports/"
      - "/packages/dart/sshnp_flutter/"
      - "/apps/admin/admin_api/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
      exclude:
      - "at_*"
    groups:
      pub:
        patterns:
          - "*"
  - package-ecosystem: 'npm'
    directory: "/apps/admin/webapp/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    groups:
      npm:
        patterns:
          - "*"
