name: noports

packages:
  - packages/dart/noports_core
  - packages/dart/sshnoports
  - packages/dart/sshnp_flutter

command:
  bootstrap:
    hooks:
      post: dart run melos exec --scope="noports_core" --scope="sshnoports" -- "dart run build_runner build --delete-conflicting-outputs"
