import 'package:at_auth/at_auth.dart';
import 'package:at_client/at_client.dart';
import 'package:mocktail/mocktail.dart';
import 'package:noports_core/commands.dart';
import 'package:noports_core/src/commands/issue_keys/issue_keys.dart';
import 'package:noports_core/src/commands/issue_keys/issue_keys_params.dart';
import 'package:test/test.dart';

import 'issue_keys_mock.dart';

class MockAtClient extends Mock implements AtClient {}

class MockEnrollmentService extends Mock implements EnrollmentService {}

class MockEnrollment extends Mock implements Enrollment {}

class FakeEnrollmentRequestDecision extends Fake
    implements EnrollmentRequestDecision {}

class FakeEnrollmentListRequestParam extends Fake
    implements EnrollmentListRequestParam {}

void main() {
  setUpAll(() {
    registerFallbackValue(FakeEnrollmentRequestDecision());
    registerFallbackValue(FakeEnrollmentListRequestParam());
  });

  group('IssueKeys', () {
    late MockAtClient mockAtClient;
    late MockEnrollmentService mockEnrollmentService;
    late IssueKeys issueKeys;
    late IssueKeysParams params;

    const testAtsign = '@impl_test';
    const testDevice = 'testDevice_123456';

    setUp(() {
      mockAtClient = MockAtClient();
      mockEnrollmentService = MockEnrollmentService();

      params = IssueKeysParams(
        atsign: testAtsign,
        device: testDevice,
        passPhrase: 'test-passphrase',
      );

      issueKeys = IssueKeysTest.test(
        params,
        atClient: mockAtClient,
        enrollmentService: mockEnrollmentService,
      );
    });

    group('IssueKeys.fromArgs factory', () {
      test('assert empty args throws', () {
        expect(() => IssueKeys.fromArgs([]), throwsA(isA<ArgumentError>()));
      });

      test('factory generates instance with valid args', () {
        List<String> testArgs = [
          '-a',
          '@alice',
          '--device',
          'my-device',
          '--pass-phrase',
          'mypass',
        ];
        expect(() => IssueKeys.fromArgs(testArgs), returnsNormally);
        // error less execution should count as success
      });

      test('factory throws with missing atsign', () {
        List<String> testArgs = [
          '--device',
          'my-device',
          '--pass-phrase',
          'mypass',
        ];
        expect(
          () => IssueKeys.fromArgs(testArgs),
          throwsA(isA<ArgumentError>()),
        );
      });

      test('factory works with just atsign', () {
        List<String> testArgs = ['-a', '@alice'];
        expect(() => IssueKeys.fromArgs(testArgs), returnsNormally);
        // error less execution should count as success
      });
    });

    group('validate behaviour of generateEnrollmentCommand() method', () {
      test('generates correct command with device name provided', () {
        params.otp = 'ABCD12';
        params.device = 'testDevice_123456';
        final command = issueKeys.generateEnrollmentCommand();

        expect(
          command,
          equals('$testAtsign:enroll:otp:ABCD12:name:testDevice_123456'),
        );
      });

      test('generates correct command without device name', () async {
        // create a new instance to ensure device name is null
        final localParams = IssueKeysParams(atsign: testAtsign, device: null);
        final localIssueKeys = IssueKeysTest.test(
          localParams,
          atClient: mockAtClient,
          enrollmentService: mockEnrollmentService,
          maxRetries: 1,
        );

        // manually triggering otp generation
        await localIssueKeys.generateOTP();
        localIssueKeys.ensureDeviceName();

        final command = localIssueKeys.generateEnrollmentCommand();
        expect(
          command,
          equals(
            '$testAtsign:enroll:otp:12345A:name:noports_12345A',
          ), // 12345A is the default OTP generated by the mock
        );
      });

      test('ensure fallback device name uses provided OTP', () {
        final params = IssueKeysParams(atsign: testAtsign)..otp = 'XYZ123';
        final issueKeys = IssueKeysTest.test(
          params,
          atClient: mockAtClient,
          enrollmentService: mockEnrollmentService,
        );

        issueKeys.ensureDeviceName();
        final command = issueKeys.generateEnrollmentCommand();
        expect(
          command,
          equals('$testAtsign:enroll:otp:XYZ123:name:noports_XYZ123'),
        );
      });
    });

    group('validate behaviour of approveEnrollment() method', () {
      test('enrollment approved successfully', () async {
        final fakeEnrollment = Enrollment()
          ..enrollmentId = 'test-id'
          ..encryptedAPKAMSymmetricKey = 'test-key';
        final mockEnrollmentResponse = AtEnrollmentResponse(
          fakeEnrollment.enrollmentId!,
          EnrollmentStatus.approved,
        );

        when(
          () => mockEnrollmentService.approve(any()),
        ).thenAnswer((_) async => mockEnrollmentResponse);

        await expectLater(
          issueKeys.approveEnrollment(fakeEnrollment),
          completes,
        ); // error less execution should count as success
      });

      test('approveEnrollment throws when enrollment not approved', () async {
        final fakeEnrollment = Enrollment()
          ..enrollmentId = 'test-id'
          ..encryptedAPKAMSymmetricKey = 'test-key';
        final mockEnrollmentResponse = AtEnrollmentResponse(
          fakeEnrollment.enrollmentId!,
          EnrollmentStatus.denied,
        );

        when(
          () => mockEnrollmentService.approve(any()),
        ).thenAnswer((_) async => mockEnrollmentResponse);

        await expectLater(
          issueKeys.approveEnrollment(fakeEnrollment),
          throwsA(isA<AtEnrollmentException>()),
        );
      });
    });

    group('validate behaviour of waitForMatchingEnrollment() method', () {
      final mockEnrollment = MockEnrollment();
      const maxAttempts = 3;
      const checkInterval = Duration(milliseconds: 100);

      setUp(() {
        issueKeys = IssueKeysTest.test(
          params,
          atClient: mockAtClient,
          enrollmentService: mockEnrollmentService,
          maxRetries: maxAttempts,
          checkInterval: checkInterval,
        );
      });

      test('polls until enrollment is found', () async {
        var callCount = 0;
        when(
          () => mockEnrollmentService.fetchEnrollmentRequests(
            enrollmentListParams: any(named: 'enrollmentListParams'),
          ),
        ).thenAnswer((_) async {
          callCount++;
          return callCount == 2 ? [mockEnrollment] : [];
        });

        final enrollment = await issueKeys.waitForMatchingEnrollment();

        expect(enrollment, equals(mockEnrollment));
        expect(callCount, equals(2));
      });

      test('waitForEnrollmentRequest returns enrollment when found', () async {
        final mockEnrollment = Enrollment()..enrollmentId = 'test-id';
        when(
          () => mockEnrollmentService.fetchEnrollmentRequests(
            enrollmentListParams: any(named: 'enrollmentListParams'),
          ),
        ).thenAnswer((_) async => [mockEnrollment]);

        final result = await issueKeys.waitForMatchingEnrollment();
        expect(result.enrollmentId, equals(mockEnrollment.enrollmentId));
      });

      test('throws AtEnrollmentException when max retries exceeded', () async {
        when(
          () => mockEnrollmentService.fetchEnrollmentRequests(
            enrollmentListParams: any(named: 'enrollmentListParams'),
          ),
        ).thenAnswer((_) async => []);

        expect(
          issueKeys.waitForMatchingEnrollment(),
          throwsA(isA<AtEnrollmentException>()),
        );
      });
    });

    group('validate behaviour of fetchMatchingEnrollment() method', () {
      test('returns enrollment when found', () async {
        final mockEnrollment = MockEnrollment();

        when(
          () => mockEnrollmentService.fetchEnrollmentRequests(
            enrollmentListParams: any(named: 'enrollmentListParams'),
          ),
        ).thenAnswer((_) async => [mockEnrollment]);

        final enrollment = await issueKeys.fetchMatchingEnrollment();
        expect(enrollment, equals(mockEnrollment));
        verify(
          () => mockEnrollmentService.fetchEnrollmentRequests(
            enrollmentListParams: any(named: 'enrollmentListParams'),
          ),
        ).called(1);
      });

      test('returns null when no enrollment found', () async {
        when(
          () => mockEnrollmentService.fetchEnrollmentRequests(
            enrollmentListParams: any(named: 'enrollmentListParams'),
          ),
        ).thenAnswer((_) async => []);

        final enrollment = await issueKeys.fetchMatchingEnrollment();
        expect(enrollment, isNull);
      });
    });
  });
}
