name: Setup entrypoints
description: |
  Sets up the environment for e2e tests.

inputs:
  sshnp:
    description: Source of the sshnp container
    required: true
  sshnp_atsign:
    description: sshnp atsign
    required: true
  sshnpd:
    description: Source of the sshnpd container
    required: true
  sshnpd_atsign:
    description: sshnpd atsign
    required: true
  sshrvd_atsign:
    description: sshrvd atsign
    required: true
  devicename:
    description: Unique sshnp devicename
    required: true
  legacy_daemon:
    description: Legacy daemon
    required: false

runs:
  using: composite
  steps:
    - name: Setup NP entrypoint
      shell: bash
      working-directory: tests/end2end_tests/contexts/_init_
      run: |
        case "${{ inputs.sshnp }}" in
          "installer")
            entrypoint_filename="sshnp_installer_entrypoint.sh"
            ;;
          *)
            entrypoint_filename="sshnp_entrypoint.sh"
            ;;
        esac
        ./setup-sshnp-entrypoint.sh ${{ inputs.devicename }} ${{ inputs.sshnp_atsign }} ${{ inputs.sshnpd_atsign }} ${{ inputs.sshrvd_atsign }} "$entrypoint_filename" ${{ inputs.legacy_daemon || false }}

    - name: Setup NPD entrypoint
      shell: bash
      working-directory: tests/end2end_tests/contexts/_init_
      run: |
        case "${{ inputs.sshnpd }}" in
          "installer")
            entrypoint_filename="sshnpd_installer_entrypoint.sh"
            ;;
          *)
            entrypoint_filename="sshnpd_entrypoint.sh"
            ;;
        esac
        echo "entrypoint_filename: $entrypoint_filename"
        ./setup-sshnpd-entrypoint.sh ${{ inputs.devicename }} ${{ inputs.sshnp_atsign }} ${{ inputs.sshnpd_atsign }} "$entrypoint_filename"

    - name: Setup RVD entrypoint
      shell: bash
      working-directory: tests/end2end_tests/contexts/_init_
      run: |
        ./setup-sshrvd-entrypoint.sh ${{ inputs.sshrvd_atsign }} "sshrvd_entrypoint.sh"
