# Dockerfile.package
# A dockerfile for packaging SSH No Ports releases using docker buildx

FROM dart:3.10.3@sha256:7240a3b57c8c755912674fcc95408ad00f4b1541397a7d54fa24a55e9deade7b AS build
WORKDIR /noports

COPY . .

# Build packages/dart/sshnoports
WORKDIR /noports/packages/dart/sshnoports
RUN set -eux; \
  mkdir -p /sshnp/debug; \
  mkdir -p /sshnp/web/admin; \
  mkdir /tarball; \
  dart pub get --enforce-lockfile; \
  dart run build_runner build --delete-conflicting-outputs; \
  dart compile exe bin/activate_cli.dart -v -o /sshnp/at_activate; \
  dart compile exe bin/sshnp.dart -v -o /sshnp/sshnp; \
  dart compile exe bin/npt.dart -v -o /sshnp/npt; \
  dart compile exe bin/npp_file.dart -v -o /sshnp/npp_file; \
  dart compile exe bin/npp_atserver.dart -v -o /sshnp/npp_atserver; \
  dart compile exe bin/sshnpd.dart -v -o /sshnp/sshnpd; \
  dart compile exe bin/srv.dart -v -o /sshnp/srv; \
  dart compile exe bin/srvd.dart -v -o /sshnp/srvd; \
  dart compile exe bin/srvd.dart -D ENABLE_SNOOP=true -v -o /sshnp/debug/srvd; \
  dart compile exe bin/npevents.dart -v -o /sshnp/npevents; \
  cp -r bundles/core/* /sshnp/; \
  cp -r bundles/shell/* /sshnp/; \
  cp LICENSE /sshnp/;

# Build apps/admin/admin_api - BETA
# Note: Only the API; webapp only included in the main platform builds
WORKDIR /noports/apps/admin/admin_api
RUN dart pub get --enforce-lockfile; \
  dart compile exe bin/np_admin.dart -v -o /sshnp/np_admin

RUN set -eux; \
  case "$(dpkg --print-architecture)" in \
  amd64) ARCH="x64";; \
  armhf) ARCH="arm";; \
  arm64) ARCH="arm64";; \
  riscv64) ARCH="riscv64";; \
  esac; \
  tar -cvzf /tarball/sshnp-linux-"${ARCH}".tgz /sshnp

FROM scratch
COPY --from=build /tarball/* /
