// Mocks generated by Mockito 5.4.5 from annotations
// in npt_flutter/test/features/profile/bloc/profile_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:npt_flutter/features/profile/profile.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i2.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Iterable<String>?> getProfileUuids() => (super.noSuchMethod(
        Invocation.method(#getProfileUuids, []),
        returnValue: _i3.Future<Iterable<String>?>.value(),
      ) as _i3.Future<Iterable<String>?>);

  @override
  _i3.Future<Iterable<_i2.Profile>> getProfiles(Iterable<String>? uuids) =>
      (super.noSuchMethod(
        Invocation.method(#getProfiles, [uuids]),
        returnValue: _i3.Future<Iterable<_i2.Profile>>.value(
          <_i2.Profile>[],
        ),
      ) as _i3.Future<Iterable<_i2.Profile>>);

  @override
  _i3.Future<_i2.Profile?> getProfile(String? uuid, {bool? useCache = true}) =>
      (super.noSuchMethod(
        Invocation.method(#getProfile, [uuid], {#useCache: useCache}),
        returnValue: _i3.Future<_i2.Profile?>.value(),
      ) as _i3.Future<_i2.Profile?>);

  @override
  _i3.Future<bool> putProfile(_i2.Profile? profile) => (super.noSuchMethod(
        Invocation.method(#putProfile, [profile]),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteProfile(String? uuid) => (super.noSuchMethod(
        Invocation.method(#deleteProfile, [uuid]),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
