version: "3.8"

services:
  image-manual-blank:
    build:
      context: ../../../
      dockerfile: ./tests/end2end_tests/image/Dockerfile
      target: manual-blank
    image: atsigncompany/sshnp-e2e-manual:blank
    deploy:
      mode: replicated
      replicas: 0
  container-sshnp:
    image: atsigncompany/sshnp-e2e-manual:blank
    container_name: manual_blank_sshnp
    volumes:
      - ../../../tests/end2end_tests/contexts/sshnp/.atsign/keys/:/atsign/.atsign/keys/ # mount keys
    networks:
      - sshnp
    depends_on:
      - image-manual-blank
  container-sshnpd:
    image: atsigncompany/sshnp-e2e-manual:blank
    container_name: manual_blank_sshnpd
    volumes:
      - ../../../tests/end2end_tests/contexts/sshnpd/.atsign/keys/:/atsign/.atsign/keys/ # mount keys
    networks:
      - sshnpd
    depends_on:
      - image-manual-blank
  container-srvd:
    image: atsigncompany/sshnp-e2e-manual:blank
    container_name: manual_blank_srvd
    volumes:
      - ../../../tests/end2end_tests/contexts/srvd/.atsign/keys/:/atsign/.atsign/keys/ # mount keys
    network_mode: host
    depends_on:
      - image-manual-blank

networks:
  sshnpd:
    name: atsigncompany/sshnp-e2e-manual-network-sshnpd
    driver: bridge
  sshnp:
    name: atsigncompany/sshnp-e2e-manual-network-sshnp
    driver: bridge
