# Configuration of sshnpd service
# This override configuration is a template for the sshnpd service.
# You can configure the service by editing the variables below.
# This service file covers the common configuration options for sshnpd.
# To see all available options, run `sshnpd` with no arguments.

[Unit]

# Uncomment the following line to make this unit fail if sshd isn't started first
; Requisite=sshd.service

# Uncomment the following line to make this unit auto-start sshd if it isn't started
; Requires=sshd.service

[Service]

# MANDATORY: User to run the daemon as
# Default value of 1000 (first non root user) should be substituted at install time
User=1000