name: noports_core
description: Core library code for sshnoports
homepage: https://docs.atsign.com/

version: 6.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  at_chops: ^1.0.7
  at_client: ^3.0.72
  at_commons: ^4.0.0
  at_utils: ^3.0.16
  cryptography: ^2.7.0
  dartssh2: ^2.8.2
  file: ^6.1.4
  logging: ^1.2.0
  meta: ^1.11.0
  openssh_ed25519: ^1.1.0
  path: ^1.9.0
  posix: ^5.0.0
  socket_connector: ^2.0.1
  uuid: ^3.0.7

dependency_overrides:
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk
      ref: trunk
      path: packages/at_client
  at_onboarding_cli:
    git:
      url: https://github.com/atsign-foundation/at_libraries
      path: packages/at_onboarding_cli
      ref: onboarding_cli_commons_uptake
  at_auth:
    git:
      url: https://github.com/atsign-foundation/at_libraries
      path: packages/at_auth
      ref: uptake_commons_into_auth
  at_server_status:
    git:
      url: https://github.com/atsign-foundation/at_libraries
      path: packages/at_server_status
      ref: update_dependencies

dev_dependencies:
  build_runner: ^2.4.8
  build_version: ^2.1.1
  lints: ^2.1.1
  mocktail: ^1.0.2
  test: ^1.25.1
