name: noports_core
description: Core library code for sshnoports
homepage: https://docs.atsign.com/
publish_to: none

version: 7.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  at_policy:
    path: ../at_policy
  args: ^2.4.2
  at_chops: ^2.0.1
  at_client: ^3.2.2
  at_commons: ^5.0.0
  at_utils: ^3.0.19
  cryptography: ^2.7.0
  dartssh2: ^2.8.2
  file: ^6.0.0
  logging: ^1.2.0
  meta: ^1.9.1
  openssh_ed25519: ^1.1.0
  path: ^1.9.0
  posix: ^6.0.1
  socket_connector: ^2.2.0
  uuid: ^3.0.7
  mutex: ^3.1.0
  json_annotation: ^4.9.0

dependency_overrides:
  at_policy:
    path: ../at_policy
  dartssh2:
    git:
      url: https://github.com/atsign-foundation/dartssh2
      ref: trunk
  args:
    git:
      ref: gkc/show-aliases-in-usage
      url: https://github.com/gkc/args

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  build_version: ^2.1.1
  lints: ^4.0.0
  mocktail: ^1.0.1
  test: ^1.24.4
