name: noports_core
description: Core library code for sshnoports
homepage: https://docs.atsign.com/

version: 5.0.4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  at_chops: ^1.0.4
  at_client: ^3.0.65
  at_commons: ^4.0.0
  at_utils: ^3.0.15
  cryptography: ^2.7.0
  dartssh2: ^2.8.2
  file: ^6.0.0
  logging: ^1.2.0
  meta: ^1.9.1
  openssh_ed25519: ^1.1.0
  path: ^1.8.3
  posix: ^5.0.0
  socket_connector: ^1.0.11
  uuid: ^3.0.7

dependency_overrides:
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: packages/at_client
      ref: trunk

dev_dependencies:
  build_runner: ^2.4.6
  build_version: ^2.1.1
  lints: ^2.1.1
  mocktail: ^1.0.1
  test: ^1.24.4
