name: noports_core
description: Core library code for sshnoports
homepage: https://docs.atsign.com/

version: 6.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  at_chops: ^2.0.0
  at_client: ^3.0.75
  at_commons: ^4.0.3
  at_utils: ^3.0.16
  cryptography: ^2.7.0
  dartssh2: ^2.8.2
  file: ^6.0.0
  logging: ^1.2.0
  meta: ^1.9.1
  openssh_ed25519: ^1.1.0
  path: ^1.9.0
  posix: ^6.0.1
  socket_connector: ^2.2.0
  uuid: ^3.0.7
  mutex: ^3.1.0

dependency_overrides:
  dartssh2:
    git:
      url: https://github.com/atsign-foundation/dartssh2
      ref: trunk
  args:
    git:
      ref: gkc/show-aliases-in-usage
      url: https://github.com/gkc/args

dev_dependencies:
  build_runner: ^2.4.6
  build_version: ^2.1.1
  lints: ^2.1.1
  mocktail: ^1.0.1
  test: ^1.24.4
