// Mocks generated by Mockito 5.4.6 from annotations
// in npt_flutter/test/features/favorite/bloc/favorite_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:npt_flutter/app.dart' as _i4;
import 'package:npt_flutter/features/favorite/favorite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FavoriteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteRepository extends _i1.Mock
    implements _i2.FavoriteRepository {
  MockFavoriteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, _i2.Favorite<_i4.Loggable>>?> getFavorites({
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFavorites, [], {#useCache: useCache}),
            returnValue:
                _i3.Future<Map<String, _i2.Favorite<_i4.Loggable>>?>.value(),
          )
          as _i3.Future<Map<String, _i2.Favorite<_i4.Loggable>>?>);

  @override
  _i3.Future<bool> addFavorite(_i2.Favorite<_i4.Loggable>? favorite) =>
      (super.noSuchMethod(
            Invocation.method(#addFavorite, [favorite]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> removeFavorites(Iterable<String>? uuids) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavorites, [uuids]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
