// Mocks generated by Mockito 5.4.6 from annotations
// in npt_flutter/test/features/profile/repository/profile_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i9;

import 'package:at_chops/at_chops.dart' as _i5;
import 'package:at_client/at_client.dart' as _i2;
import 'package:at_client/src/listener/at_sign_change_listener.dart' as _i11;
import 'package:at_client/src/response/response.dart' as _i3;
import 'package:at_client/src/stream/at_stream_response.dart' as _i4;
import 'package:at_client/src/stream/file_transfer_object.dart' as _i8;
import 'package:at_lookup/at_lookup.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSyncService_0 extends _i1.SmartFake implements _i2.SyncService {
  _FakeSyncService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationService_1 extends _i1.SmartFake
    implements _i2.NotificationService {
  _FakeNotificationService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtResponse_2 extends _i1.SmartFake implements _i3.AtResponse {
  _FakeAtResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtValue_3 extends _i1.SmartFake implements _i2.AtValue {
  _FakeAtValue_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtStreamResponse_4 extends _i1.SmartFake
    implements _i4.AtStreamResponse {
  _FakeAtStreamResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtClient_5 extends _i1.SmartFake implements _i2.AtClient {
  _FakeAtClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtClientManager_6 extends _i1.SmartFake
    implements _i2.AtClientManager {
  _FakeAtClientManager_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIterator_7<E> extends _i1.SmartFake implements Iterator<E> {
  _FakeIterator_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AtClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtClient extends _i1.Mock implements _i2.AtClient {
  MockAtClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SyncService get syncService =>
      (super.noSuchMethod(
            Invocation.getter(#syncService),
            returnValue: _FakeSyncService_0(
              this,
              Invocation.getter(#syncService),
            ),
          )
          as _i2.SyncService);

  @override
  _i2.NotificationService get notificationService =>
      (super.noSuchMethod(
            Invocation.getter(#notificationService),
            returnValue: _FakeNotificationService_1(
              this,
              Invocation.getter(#notificationService),
            ),
          )
          as _i2.NotificationService);

  @override
  set telemetry(_i2.AtTelemetryService? telemetryService) => super.noSuchMethod(
    Invocation.setter(#telemetry, telemetryService),
    returnValueForMissingStub: null,
  );

  @override
  set atChops(_i5.AtChops? atChops) => super.noSuchMethod(
    Invocation.setter(#atChops, atChops),
    returnValueForMissingStub: null,
  );

  @override
  set enrollmentId(String? enrollmentId) => super.noSuchMethod(
    Invocation.setter(#enrollmentId, enrollmentId),
    returnValueForMissingStub: null,
  );

  @override
  set syncService(_i2.SyncService? syncService) => super.noSuchMethod(
    Invocation.setter(#syncService, syncService),
    returnValueForMissingStub: null,
  );

  @override
  set notificationService(_i2.NotificationService? notificationService) =>
      super.noSuchMethod(
        Invocation.setter(#notificationService, notificationService),
        returnValueForMissingStub: null,
      );

  @override
  set enrollmentService(_i2.EnrollmentService? enrollmentService) =>
      super.noSuchMethod(
        Invocation.setter(#enrollmentService, enrollmentService),
        returnValueForMissingStub: null,
      );

  @override
  void setPreferences(_i2.AtClientPreference? preference) => super.noSuchMethod(
    Invocation.method(#setPreferences, [preference]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool> put(
    _i2.AtKey? key,
    dynamic value, {
    bool? isDedicated = false,
    _i2.PutRequestOptions? putRequestOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [key, value],
              {
                #isDedicated: isDedicated,
                #putRequestOptions: putRequestOptions,
              },
            ),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i3.AtResponse> putText(
    _i2.AtKey? atKey,
    String? value, {
    _i2.PutRequestOptions? putRequestOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putText,
              [atKey, value],
              {#putRequestOptions: putRequestOptions},
            ),
            returnValue: _i6.Future<_i3.AtResponse>.value(
              _FakeAtResponse_2(
                this,
                Invocation.method(
                  #putText,
                  [atKey, value],
                  {#putRequestOptions: putRequestOptions},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.AtResponse>);

  @override
  _i6.Future<_i3.AtResponse> putBinary(
    _i2.AtKey? atKey,
    List<int>? value, {
    _i2.PutRequestOptions? putRequestOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putBinary,
              [atKey, value],
              {#putRequestOptions: putRequestOptions},
            ),
            returnValue: _i6.Future<_i3.AtResponse>.value(
              _FakeAtResponse_2(
                this,
                Invocation.method(
                  #putBinary,
                  [atKey, value],
                  {#putRequestOptions: putRequestOptions},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.AtResponse>);

  @override
  _i6.Future<bool> putMeta(
    _i2.AtKey? key, {
    _i2.PutRequestOptions? putRequestOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putMeta,
              [key],
              {#putRequestOptions: putRequestOptions},
            ),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i2.AtValue> get(
    _i2.AtKey? key, {
    bool? isDedicated = false,
    _i2.GetRequestOptions? getRequestOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [key],
              {
                #isDedicated: isDedicated,
                #getRequestOptions: getRequestOptions,
              },
            ),
            returnValue: _i6.Future<_i2.AtValue>.value(
              _FakeAtValue_3(
                this,
                Invocation.method(
                  #get,
                  [key],
                  {
                    #isDedicated: isDedicated,
                    #getRequestOptions: getRequestOptions,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.AtValue>);

  @override
  _i6.Future<_i2.Metadata?> getMeta(_i2.AtKey? key) =>
      (super.noSuchMethod(
            Invocation.method(#getMeta, [key]),
            returnValue: _i6.Future<_i2.Metadata?>.value(),
          )
          as _i6.Future<_i2.Metadata?>);

  @override
  _i6.Future<bool> delete(
    _i2.AtKey? key, {
    bool? isDedicated = false,
    _i2.DeleteRequestOptions? deleteRequestOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [key],
              {
                #isDedicated: isDedicated,
                #deleteRequestOptions: deleteRequestOptions,
              },
            ),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<_i2.AtKey>> getAtKeys({
    String? regex,
    String? sharedBy,
    String? sharedWith,
    bool? showHiddenKeys = false,
    bool? useRemoteAtServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAtKeys, [], {
              #regex: regex,
              #sharedBy: sharedBy,
              #sharedWith: sharedWith,
              #showHiddenKeys: showHiddenKeys,
              #useRemoteAtServer: useRemoteAtServer,
            }),
            returnValue: _i6.Future<List<_i2.AtKey>>.value(<_i2.AtKey>[]),
          )
          as _i6.Future<List<_i2.AtKey>>);

  @override
  _i6.Future<List<String>> getKeys({
    String? regex,
    String? sharedBy,
    String? sharedWith,
    bool? showHiddenKeys = false,
    bool? useRemoteAtServer = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, [], {
              #regex: regex,
              #sharedBy: sharedBy,
              #sharedWith: sharedWith,
              #showHiddenKeys: showHiddenKeys,
              #useRemoteAtServer: useRemoteAtServer,
            }),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<bool> notify(
    _i2.AtKey? key,
    String? value,
    _i2.OperationEnum? operation, {
    _i2.MessageTypeEnum? messageType,
    _i2.PriorityEnum? priority,
    _i2.StrategyEnum? strategy,
    int? latestN,
    String? notifier,
    bool? isDedicated = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #notify,
              [key, value, operation],
              {
                #messageType: messageType,
                #priority: priority,
                #strategy: strategy,
                #latestN: latestN,
                #notifier: notifier,
                #isDedicated: isDedicated,
              },
            ),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<String?> notifyChange(
    _i2.NotificationParams? notificationParams,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#notifyChange, [notificationParams]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String> notifyAll(
    _i2.AtKey? atKey,
    String? value,
    _i2.OperationEnum? operation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#notifyAll, [atKey, value, operation]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#notifyAll, [atKey, value, operation]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> notifyStatus(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#notifyStatus, [notificationId]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#notifyStatus, [notificationId]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> notifyList({
    String? fromDate,
    String? toDate,
    String? regex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyList, [], {
              #fromDate: fromDate,
              #toDate: toDate,
              #regex: regex,
            }),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#notifyList, [], {
                  #fromDate: fromDate,
                  #toDate: toDate,
                  #regex: regex,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> startMonitor(
    String? privateKey,
    Function? acceptStream, {
    String? regex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startMonitor,
              [privateKey, acceptStream],
              {#regex: regex},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.AtStreamResponse> stream(
    String? sharedWith,
    String? filePath, {
    String? namespace,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #stream,
              [sharedWith, filePath],
              {#namespace: namespace},
            ),
            returnValue: _i6.Future<_i4.AtStreamResponse>.value(
              _FakeAtStreamResponse_4(
                this,
                Invocation.method(
                  #stream,
                  [sharedWith, filePath],
                  {#namespace: namespace},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.AtStreamResponse>);

  @override
  _i6.Future<void> sendStreamAck(
    String? streamId,
    String? fileName,
    int? fileLength,
    String? senderAtSign,
    Function? streamCompletionCallBack,
    Function? streamReceiveCallBack,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendStreamAck, [
              streamId,
              fileName,
              fileLength,
              senderAtSign,
              streamCompletionCallBack,
              streamReceiveCallBack,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.AtResponse> setSPP(String? otp) =>
      (super.noSuchMethod(
            Invocation.method(#setSPP, [otp]),
            returnValue: _i6.Future<_i3.AtResponse>.value(
              _FakeAtResponse_2(this, Invocation.method(#setSPP, [otp])),
            ),
          )
          as _i6.Future<_i3.AtResponse>);

  @override
  _i6.Future<_i3.AtResponse> getOTP() =>
      (super.noSuchMethod(
            Invocation.method(#getOTP, []),
            returnValue: _i6.Future<_i3.AtResponse>.value(
              _FakeAtResponse_2(this, Invocation.method(#getOTP, [])),
            ),
          )
          as _i6.Future<_i3.AtResponse>);

  @override
  _i6.Future<void> startCompactionJob({
    Duration? commitLogCompactionDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startCompactionJob, [], {
              #commitLogCompactionDuration: commitLogCompactionDuration,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> stopCompactionJob() =>
      (super.noSuchMethod(
            Invocation.method(#stopCompactionJob, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, _i8.FileTransferObject>> uploadFile(
    List<_i9.File>? files,
    List<String>? sharedWithAtSigns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [files, sharedWithAtSigns]),
            returnValue: _i6.Future<Map<String, _i8.FileTransferObject>>.value(
              <String, _i8.FileTransferObject>{},
            ),
          )
          as _i6.Future<Map<String, _i8.FileTransferObject>>);

  @override
  _i6.Future<List<_i9.File>> downloadFile(
    String? transferId,
    String? sharedByAtSign, {
    String? downloadPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadFile,
              [transferId, sharedByAtSign],
              {#downloadPath: downloadPath},
            ),
            returnValue: _i6.Future<List<_i9.File>>.value(<_i9.File>[]),
          )
          as _i6.Future<List<_i9.File>>);

  @override
  _i6.Future<List<_i8.FileStatus>> reuploadFiles(
    List<_i9.File>? files,
    _i8.FileTransferObject? fileTransferObject,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reuploadFiles, [files, fileTransferObject]),
            returnValue: _i6.Future<List<_i8.FileStatus>>.value(
              <_i8.FileStatus>[],
            ),
          )
          as _i6.Future<List<_i8.FileStatus>>);

  @override
  _i6.Future<Map<String, _i8.FileTransferObject>> shareFiles(
    List<String>? sharedWithAtSigns,
    String? key,
    String? fileUrl,
    String? encryptionKey,
    List<_i8.FileStatus>? fileStatus, {
    DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #shareFiles,
              [sharedWithAtSigns, key, fileUrl, encryptionKey, fileStatus],
              {#date: date},
            ),
            returnValue: _i6.Future<Map<String, _i8.FileTransferObject>>.value(
              <String, _i8.FileTransferObject>{},
            ),
          )
          as _i6.Future<Map<String, _i8.FileTransferObject>>);
}

/// A class which mocks [AtClientManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtClientManager extends _i1.Mock implements _i2.AtClientManager {
  MockAtClientManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AtClient get atClient =>
      (super.noSuchMethod(
            Invocation.getter(#atClient),
            returnValue: _FakeAtClient_5(this, Invocation.getter(#atClient)),
          )
          as _i2.AtClient);

  @override
  _i2.SyncService get syncService =>
      (super.noSuchMethod(
            Invocation.getter(#syncService),
            returnValue: _FakeSyncService_0(
              this,
              Invocation.getter(#syncService),
            ),
          )
          as _i2.SyncService);

  @override
  _i2.NotificationService get notificationService =>
      (super.noSuchMethod(
            Invocation.getter(#notificationService),
            returnValue: _FakeNotificationService_1(
              this,
              Invocation.getter(#notificationService),
            ),
          )
          as _i2.NotificationService);

  @override
  set secondaryAddressFinder(_i10.SecondaryAddressFinder? value) =>
      super.noSuchMethod(
        Invocation.setter(#secondaryAddressFinder, value),
        returnValueForMissingStub: null,
      );

  @override
  void setSecondaryAddressFinder({
    _i10.SecondaryAddressFinder? secondaryAddressFinder,
  }) => super.noSuchMethod(
    Invocation.method(#setSecondaryAddressFinder, [], {
      #secondaryAddressFinder: secondaryAddressFinder,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i2.AtClientManager> setCurrentAtSign(
    String? atSign,
    String? namespace,
    _i2.AtClientPreference? preference, {
    _i2.AtServiceFactory? serviceFactory,
    _i5.AtChops? atChops,
    _i10.AtLookUp? atLookUp,
    String? enrollmentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setCurrentAtSign,
              [atSign, namespace, preference],
              {
                #serviceFactory: serviceFactory,
                #atChops: atChops,
                #atLookUp: atLookUp,
                #enrollmentId: enrollmentId,
              },
            ),
            returnValue: _i6.Future<_i2.AtClientManager>.value(
              _FakeAtClientManager_6(
                this,
                Invocation.method(
                  #setCurrentAtSign,
                  [atSign, namespace, preference],
                  {
                    #serviceFactory: serviceFactory,
                    #atChops: atChops,
                    #atLookUp: atLookUp,
                    #enrollmentId: enrollmentId,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.AtClientManager>);

  @override
  void listenToAtSignChange(_i11.AtSignChangeListener? listener) =>
      super.noSuchMethod(
        Invocation.method(#listenToAtSignChange, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void removeChangeListeners(_i11.AtSignChangeListener? atSignChangeListener) =>
      super.noSuchMethod(
        Invocation.method(#removeChangeListeners, [atSignChangeListener]),
        returnValueForMissingStub: null,
      );

  @override
  int getChangeListenersSize() =>
      (super.noSuchMethod(
            Invocation.method(#getChangeListenersSize, []),
            returnValue: 0,
          )
          as int);

  @override
  Iterator<dynamic> getItemsInChangeListeners() =>
      (super.noSuchMethod(
            Invocation.method(#getItemsInChangeListeners, []),
            returnValue: _FakeIterator_7<dynamic>(
              this,
              Invocation.method(#getItemsInChangeListeners, []),
            ),
          )
          as Iterator<dynamic>);

  @override
  void removeAllChangeListeners() => super.noSuchMethod(
    Invocation.method(#removeAllChangeListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );
}
