// Mocks generated by Mockito 5.4.5 from annotations
// in npt_flutter/test/features/profile/repository/profile_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i11;

import 'package:at_chops/at_chops.dart' as _i7;
import 'package:at_client/at_client.dart' as _i2;
import 'package:at_client/src/listener/at_sign_change_listener.dart' as _i13;
import 'package:at_client/src/preference/at_client_particulars.dart' as _i6;
import 'package:at_client/src/response/response.dart' as _i3;
import 'package:at_client/src/stream/at_stream_response.dart' as _i4;
import 'package:at_client/src/stream/file_transfer_object.dart' as _i10;
import 'package:at_lookup/at_lookup.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:version/version.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncService_0 extends _i1.SmartFake implements _i2.SyncService {
  _FakeSyncService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationService_1 extends _i1.SmartFake
    implements _i2.NotificationService {
  _FakeNotificationService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtResponse_2 extends _i1.SmartFake implements _i3.AtResponse {
  _FakeAtResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtValue_3 extends _i1.SmartFake implements _i2.AtValue {
  _FakeAtValue_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtStreamResponse_4 extends _i1.SmartFake
    implements _i4.AtStreamResponse {
  _FakeAtStreamResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtClient_5 extends _i1.SmartFake implements _i2.AtClient {
  _FakeAtClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtClientManager_6 extends _i1.SmartFake
    implements _i2.AtClientManager {
  _FakeAtClientManager_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIterator_7<E> extends _i1.SmartFake implements Iterator<E> {
  _FakeIterator_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_8 extends _i1.SmartFake implements Duration {
  _FakeDuration_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVersion_9 extends _i1.SmartFake implements _i5.Version {
  _FakeVersion_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAtClientParticulars_10 extends _i1.SmartFake
    implements _i6.AtClientParticulars {
  _FakeAtClientParticulars_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AtClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtClient extends _i1.Mock implements _i2.AtClient {
  MockAtClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set telemetry(_i2.AtTelemetryService? telemetryService) => super.noSuchMethod(
    Invocation.setter(#telemetry, telemetryService),
    returnValueForMissingStub: null,
  );

  @override
  set atChops(_i7.AtChops? atChops) => super.noSuchMethod(
    Invocation.setter(#atChops, atChops),
    returnValueForMissingStub: null,
  );

  @override
  set enrollmentId(String? enrollmentId) => super.noSuchMethod(
    Invocation.setter(#enrollmentId, enrollmentId),
    returnValueForMissingStub: null,
  );

  @override
  set syncService(_i2.SyncService? syncService) => super.noSuchMethod(
    Invocation.setter(#syncService, syncService),
    returnValueForMissingStub: null,
  );

  @override
  _i2.SyncService get syncService =>
      (super.noSuchMethod(
            Invocation.getter(#syncService),
            returnValue: _FakeSyncService_0(
              this,
              Invocation.getter(#syncService),
            ),
          )
          as _i2.SyncService);

  @override
  set notificationService(_i2.NotificationService? notificationService) =>
      super.noSuchMethod(
        Invocation.setter(#notificationService, notificationService),
        returnValueForMissingStub: null,
      );

  @override
  _i2.NotificationService get notificationService =>
      (super.noSuchMethod(
            Invocation.getter(#notificationService),
            returnValue: _FakeNotificationService_1(
              this,
              Invocation.getter(#notificationService),
            ),
          )
          as _i2.NotificationService);

  @override
  set enrollmentService(_i2.EnrollmentService? enrollmentService) =>
      super.noSuchMethod(
        Invocation.setter(#enrollmentService, enrollmentService),
        returnValueForMissingStub: null,
      );

  @override
  void setPreferences(_i2.AtClientPreference? preference) => super.noSuchMethod(
    Invocation.method(#setPreferences, [preference]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> put(
    _i2.AtKey? key,
    dynamic value, {
    bool? isDedicated = false,
    _i2.PutRequestOptions? putRequestOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [key, value],
              {
                #isDedicated: isDedicated,
                #putRequestOptions: putRequestOptions,
              },
            ),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i3.AtResponse> putText(
    _i2.AtKey? atKey,
    String? value, {
    _i2.PutRequestOptions? putRequestOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putText,
              [atKey, value],
              {#putRequestOptions: putRequestOptions},
            ),
            returnValue: _i8.Future<_i3.AtResponse>.value(
              _FakeAtResponse_2(
                this,
                Invocation.method(
                  #putText,
                  [atKey, value],
                  {#putRequestOptions: putRequestOptions},
                ),
              ),
            ),
          )
          as _i8.Future<_i3.AtResponse>);

  @override
  _i8.Future<_i3.AtResponse> putBinary(
    _i2.AtKey? atKey,
    List<int>? value, {
    _i2.PutRequestOptions? putRequestOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putBinary,
              [atKey, value],
              {#putRequestOptions: putRequestOptions},
            ),
            returnValue: _i8.Future<_i3.AtResponse>.value(
              _FakeAtResponse_2(
                this,
                Invocation.method(
                  #putBinary,
                  [atKey, value],
                  {#putRequestOptions: putRequestOptions},
                ),
              ),
            ),
          )
          as _i8.Future<_i3.AtResponse>);

  @override
  _i8.Future<bool> putMeta(_i2.AtKey? key) =>
      (super.noSuchMethod(
            Invocation.method(#putMeta, [key]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i2.AtValue> get(
    _i2.AtKey? key, {
    bool? isDedicated = false,
    _i2.GetRequestOptions? getRequestOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [key],
              {
                #isDedicated: isDedicated,
                #getRequestOptions: getRequestOptions,
              },
            ),
            returnValue: _i8.Future<_i2.AtValue>.value(
              _FakeAtValue_3(
                this,
                Invocation.method(
                  #get,
                  [key],
                  {
                    #isDedicated: isDedicated,
                    #getRequestOptions: getRequestOptions,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i2.AtValue>);

  @override
  _i8.Future<_i2.Metadata?> getMeta(_i2.AtKey? key) =>
      (super.noSuchMethod(
            Invocation.method(#getMeta, [key]),
            returnValue: _i8.Future<_i2.Metadata?>.value(),
          )
          as _i8.Future<_i2.Metadata?>);

  @override
  _i8.Future<bool> delete(
    _i2.AtKey? key, {
    bool? isDedicated = false,
    _i2.DeleteRequestOptions? deleteRequestOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [key],
              {
                #isDedicated: isDedicated,
                #deleteRequestOptions: deleteRequestOptions,
              },
            ),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<_i2.AtKey>> getAtKeys({
    String? regex,
    String? sharedBy,
    String? sharedWith,
    bool? showHiddenKeys = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAtKeys, [], {
              #regex: regex,
              #sharedBy: sharedBy,
              #sharedWith: sharedWith,
              #showHiddenKeys: showHiddenKeys,
            }),
            returnValue: _i8.Future<List<_i2.AtKey>>.value(<_i2.AtKey>[]),
          )
          as _i8.Future<List<_i2.AtKey>>);

  @override
  _i8.Future<List<String>> getKeys({
    String? regex,
    String? sharedBy,
    String? sharedWith,
    bool? showHiddenKeys = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, [], {
              #regex: regex,
              #sharedBy: sharedBy,
              #sharedWith: sharedWith,
              #showHiddenKeys: showHiddenKeys,
            }),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<bool> notify(
    _i2.AtKey? key,
    String? value,
    _i2.OperationEnum? operation, {
    _i2.MessageTypeEnum? messageType,
    _i2.PriorityEnum? priority,
    _i2.StrategyEnum? strategy,
    int? latestN,
    String? notifier,
    bool? isDedicated = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #notify,
              [key, value, operation],
              {
                #messageType: messageType,
                #priority: priority,
                #strategy: strategy,
                #latestN: latestN,
                #notifier: notifier,
                #isDedicated: isDedicated,
              },
            ),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<String?> notifyChange(
    _i2.NotificationParams? notificationParams,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#notifyChange, [notificationParams]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<String> notifyAll(
    _i2.AtKey? atKey,
    String? value,
    _i2.OperationEnum? operation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#notifyAll, [atKey, value, operation]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#notifyAll, [atKey, value, operation]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> notifyStatus(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#notifyStatus, [notificationId]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#notifyStatus, [notificationId]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> notifyList({
    String? fromDate,
    String? toDate,
    String? regex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyList, [], {
              #fromDate: fromDate,
              #toDate: toDate,
              #regex: regex,
            }),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#notifyList, [], {
                  #fromDate: fromDate,
                  #toDate: toDate,
                  #regex: regex,
                }),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> startMonitor(
    String? privateKey,
    Function? acceptStream, {
    String? regex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startMonitor,
              [privateKey, acceptStream],
              {#regex: regex},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i4.AtStreamResponse> stream(
    String? sharedWith,
    String? filePath, {
    String? namespace,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #stream,
              [sharedWith, filePath],
              {#namespace: namespace},
            ),
            returnValue: _i8.Future<_i4.AtStreamResponse>.value(
              _FakeAtStreamResponse_4(
                this,
                Invocation.method(
                  #stream,
                  [sharedWith, filePath],
                  {#namespace: namespace},
                ),
              ),
            ),
          )
          as _i8.Future<_i4.AtStreamResponse>);

  @override
  _i8.Future<void> sendStreamAck(
    String? streamId,
    String? fileName,
    int? fileLength,
    String? senderAtSign,
    Function? streamCompletionCallBack,
    Function? streamReceiveCallBack,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendStreamAck, [
              streamId,
              fileName,
              fileLength,
              senderAtSign,
              streamCompletionCallBack,
              streamReceiveCallBack,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.AtResponse> setSPP(String? otp) =>
      (super.noSuchMethod(
            Invocation.method(#setSPP, [otp]),
            returnValue: _i8.Future<_i3.AtResponse>.value(
              _FakeAtResponse_2(this, Invocation.method(#setSPP, [otp])),
            ),
          )
          as _i8.Future<_i3.AtResponse>);

  @override
  _i8.Future<_i3.AtResponse> getOTP() =>
      (super.noSuchMethod(
            Invocation.method(#getOTP, []),
            returnValue: _i8.Future<_i3.AtResponse>.value(
              _FakeAtResponse_2(this, Invocation.method(#getOTP, [])),
            ),
          )
          as _i8.Future<_i3.AtResponse>);

  @override
  _i8.Future<void> startCompactionJob({
    Duration? commitLogCompactionDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startCompactionJob, [], {
              #commitLogCompactionDuration: commitLogCompactionDuration,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> stopCompactionJob() =>
      (super.noSuchMethod(
            Invocation.method(#stopCompactionJob, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, _i10.FileTransferObject>> uploadFile(
    List<_i11.File>? files,
    List<String>? sharedWithAtSigns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [files, sharedWithAtSigns]),
            returnValue: _i8.Future<Map<String, _i10.FileTransferObject>>.value(
              <String, _i10.FileTransferObject>{},
            ),
          )
          as _i8.Future<Map<String, _i10.FileTransferObject>>);

  @override
  _i8.Future<List<_i11.File>> downloadFile(
    String? transferId,
    String? sharedByAtSign, {
    String? downloadPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadFile,
              [transferId, sharedByAtSign],
              {#downloadPath: downloadPath},
            ),
            returnValue: _i8.Future<List<_i11.File>>.value(<_i11.File>[]),
          )
          as _i8.Future<List<_i11.File>>);

  @override
  _i8.Future<List<_i10.FileStatus>> reuploadFiles(
    List<_i11.File>? files,
    _i10.FileTransferObject? fileTransferObject,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reuploadFiles, [files, fileTransferObject]),
            returnValue: _i8.Future<List<_i10.FileStatus>>.value(
              <_i10.FileStatus>[],
            ),
          )
          as _i8.Future<List<_i10.FileStatus>>);

  @override
  _i8.Future<Map<String, _i10.FileTransferObject>> shareFiles(
    List<String>? sharedWithAtSigns,
    String? key,
    String? fileUrl,
    String? encryptionKey,
    List<_i10.FileStatus>? fileStatus, {
    DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #shareFiles,
              [sharedWithAtSigns, key, fileUrl, encryptionKey, fileStatus],
              {#date: date},
            ),
            returnValue: _i8.Future<Map<String, _i10.FileTransferObject>>.value(
              <String, _i10.FileTransferObject>{},
            ),
          )
          as _i8.Future<Map<String, _i10.FileTransferObject>>);
}

/// A class which mocks [AtClientManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtClientManager extends _i1.Mock implements _i2.AtClientManager {
  MockAtClientManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set secondaryAddressFinder(
    _i12.SecondaryAddressFinder? _secondaryAddressFinder,
  ) => super.noSuchMethod(
    Invocation.setter(#secondaryAddressFinder, _secondaryAddressFinder),
    returnValueForMissingStub: null,
  );

  @override
  _i2.AtClient get atClient =>
      (super.noSuchMethod(
            Invocation.getter(#atClient),
            returnValue: _FakeAtClient_5(this, Invocation.getter(#atClient)),
          )
          as _i2.AtClient);

  @override
  _i2.SyncService get syncService =>
      (super.noSuchMethod(
            Invocation.getter(#syncService),
            returnValue: _FakeSyncService_0(
              this,
              Invocation.getter(#syncService),
            ),
          )
          as _i2.SyncService);

  @override
  _i2.NotificationService get notificationService =>
      (super.noSuchMethod(
            Invocation.getter(#notificationService),
            returnValue: _FakeNotificationService_1(
              this,
              Invocation.getter(#notificationService),
            ),
          )
          as _i2.NotificationService);

  @override
  void setSecondaryAddressFinder({
    _i12.SecondaryAddressFinder? secondaryAddressFinder,
  }) => super.noSuchMethod(
    Invocation.method(#setSecondaryAddressFinder, [], {
      #secondaryAddressFinder: secondaryAddressFinder,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i2.AtClientManager> setCurrentAtSign(
    String? atSign,
    String? namespace,
    _i2.AtClientPreference? preference, {
    _i2.AtServiceFactory? serviceFactory,
    _i7.AtChops? atChops,
    String? enrollmentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setCurrentAtSign,
              [atSign, namespace, preference],
              {
                #serviceFactory: serviceFactory,
                #atChops: atChops,
                #enrollmentId: enrollmentId,
              },
            ),
            returnValue: _i8.Future<_i2.AtClientManager>.value(
              _FakeAtClientManager_6(
                this,
                Invocation.method(
                  #setCurrentAtSign,
                  [atSign, namespace, preference],
                  {
                    #serviceFactory: serviceFactory,
                    #atChops: atChops,
                    #enrollmentId: enrollmentId,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i2.AtClientManager>);

  @override
  void listenToAtSignChange(_i13.AtSignChangeListener? listener) =>
      super.noSuchMethod(
        Invocation.method(#listenToAtSignChange, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void removeChangeListeners(_i13.AtSignChangeListener? atSignChangeListener) =>
      super.noSuchMethod(
        Invocation.method(#removeChangeListeners, [atSignChangeListener]),
        returnValueForMissingStub: null,
      );

  @override
  int getChangeListenersSize() =>
      (super.noSuchMethod(
            Invocation.method(#getChangeListenersSize, []),
            returnValue: 0,
          )
          as int);

  @override
  Iterator<dynamic> getItemsInChangeListeners() =>
      (super.noSuchMethod(
            Invocation.method(#getItemsInChangeListeners, []),
            returnValue: _FakeIterator_7<dynamic>(
              this,
              Invocation.method(#getItemsInChangeListeners, []),
            ),
          )
          as Iterator<dynamic>);

  @override
  void removeAllChangeListeners() => super.noSuchMethod(
    Invocation.method(#removeAllChangeListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AtClientPreference].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtClientPreference extends _i1.Mock
    implements _i2.AtClientPreference {
  MockAtClientPreference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set hiveStoragePath(String? _hiveStoragePath) => super.noSuchMethod(
    Invocation.setter(#hiveStoragePath, _hiveStoragePath),
    returnValueForMissingStub: null,
  );

  @override
  set commitLogPath(String? _commitLogPath) => super.noSuchMethod(
    Invocation.setter(#commitLogPath, _commitLogPath),
    returnValueForMissingStub: null,
  );

  @override
  set syncStrategy(_i2.SyncStrategy? _syncStrategy) => super.noSuchMethod(
    Invocation.setter(#syncStrategy, _syncStrategy),
    returnValueForMissingStub: null,
  );

  @override
  bool get isLocalStoreRequired =>
      (super.noSuchMethod(
            Invocation.getter(#isLocalStoreRequired),
            returnValue: false,
          )
          as bool);

  @override
  set isLocalStoreRequired(bool? _isLocalStoreRequired) => super.noSuchMethod(
    Invocation.setter(#isLocalStoreRequired, _isLocalStoreRequired),
    returnValueForMissingStub: null,
  );

  @override
  set cramSecret(String? _cramSecret) => super.noSuchMethod(
    Invocation.setter(#cramSecret, _cramSecret),
    returnValueForMissingStub: null,
  );

  @override
  set privateKey(String? _privateKey) => super.noSuchMethod(
    Invocation.setter(#privateKey, _privateKey),
    returnValueForMissingStub: null,
  );

  @override
  set namespace(String? _namespace) => super.noSuchMethod(
    Invocation.setter(#namespace, _namespace),
    returnValueForMissingStub: null,
  );

  @override
  set keyStoreSecret(List<int>? _keyStoreSecret) => super.noSuchMethod(
    Invocation.setter(#keyStoreSecret, _keyStoreSecret),
    returnValueForMissingStub: null,
  );

  @override
  String get rootDomain =>
      (super.noSuchMethod(
            Invocation.getter(#rootDomain),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#rootDomain),
            ),
          )
          as String);

  @override
  set rootDomain(String? _rootDomain) => super.noSuchMethod(
    Invocation.setter(#rootDomain, _rootDomain),
    returnValueForMissingStub: null,
  );

  @override
  int get rootPort =>
      (super.noSuchMethod(Invocation.getter(#rootPort), returnValue: 0) as int);

  @override
  set rootPort(int? _rootPort) => super.noSuchMethod(
    Invocation.setter(#rootPort, _rootPort),
    returnValueForMissingStub: null,
  );

  @override
  int get syncIntervalMins =>
      (super.noSuchMethod(Invocation.getter(#syncIntervalMins), returnValue: 0)
          as int);

  @override
  set syncIntervalMins(int? _syncIntervalMins) => super.noSuchMethod(
    Invocation.setter(#syncIntervalMins, _syncIntervalMins),
    returnValueForMissingStub: null,
  );

  @override
  int get outboundConnectionTimeout =>
      (super.noSuchMethod(
            Invocation.getter(#outboundConnectionTimeout),
            returnValue: 0,
          )
          as int);

  @override
  set outboundConnectionTimeout(int? _outboundConnectionTimeout) =>
      super.noSuchMethod(
        Invocation.setter(
          #outboundConnectionTimeout,
          _outboundConnectionTimeout,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get maxDataSize =>
      (super.noSuchMethod(Invocation.getter(#maxDataSize), returnValue: 0)
          as int);

  @override
  set maxDataSize(int? _maxDataSize) => super.noSuchMethod(
    Invocation.setter(#maxDataSize, _maxDataSize),
    returnValueForMissingStub: null,
  );

  @override
  set downloadPath(String? _downloadPath) => super.noSuchMethod(
    Invocation.setter(#downloadPath, _downloadPath),
    returnValueForMissingStub: null,
  );

  @override
  set syncRegex(String? _syncRegex) => super.noSuchMethod(
    Invocation.setter(#syncRegex, _syncRegex),
    returnValueForMissingStub: null,
  );

  @override
  int get syncBatchSize =>
      (super.noSuchMethod(Invocation.getter(#syncBatchSize), returnValue: 0)
          as int);

  @override
  set syncBatchSize(int? _syncBatchSize) => super.noSuchMethod(
    Invocation.setter(#syncBatchSize, _syncBatchSize),
    returnValueForMissingStub: null,
  );

  @override
  int get syncPageLimit =>
      (super.noSuchMethod(Invocation.getter(#syncPageLimit), returnValue: 0)
          as int);

  @override
  set syncPageLimit(int? _syncPageLimit) => super.noSuchMethod(
    Invocation.setter(#syncPageLimit, _syncPageLimit),
    returnValueForMissingStub: null,
  );

  @override
  int get fileEncryptionChunkSize =>
      (super.noSuchMethod(
            Invocation.getter(#fileEncryptionChunkSize),
            returnValue: 0,
          )
          as int);

  @override
  set fileEncryptionChunkSize(int? _fileEncryptionChunkSize) =>
      super.noSuchMethod(
        Invocation.setter(#fileEncryptionChunkSize, _fileEncryptionChunkSize),
        returnValueForMissingStub: null,
      );

  @override
  Duration get monitorHeartbeatInterval =>
      (super.noSuchMethod(
            Invocation.getter(#monitorHeartbeatInterval),
            returnValue: _FakeDuration_8(
              this,
              Invocation.getter(#monitorHeartbeatInterval),
            ),
          )
          as Duration);

  @override
  set monitorHeartbeatInterval(Duration? _monitorHeartbeatInterval) =>
      super.noSuchMethod(
        Invocation.setter(#monitorHeartbeatInterval, _monitorHeartbeatInterval),
        returnValueForMissingStub: null,
      );

  @override
  Duration get expiryCheckTimeInterval =>
      (super.noSuchMethod(
            Invocation.getter(#expiryCheckTimeInterval),
            returnValue: _FakeDuration_8(
              this,
              Invocation.getter(#expiryCheckTimeInterval),
            ),
          )
          as Duration);

  @override
  set expiryCheckTimeInterval(Duration? _expiryCheckTimeInterval) =>
      super.noSuchMethod(
        Invocation.setter(#expiryCheckTimeInterval, _expiryCheckTimeInterval),
        returnValueForMissingStub: null,
      );

  @override
  bool get decryptPackets =>
      (super.noSuchMethod(
            Invocation.getter(#decryptPackets),
            returnValue: false,
          )
          as bool);

  @override
  set decryptPackets(bool? _decryptPackets) => super.noSuchMethod(
    Invocation.setter(#decryptPackets, _decryptPackets),
    returnValueForMissingStub: null,
  );

  @override
  set tlsKeysSavePath(String? _tlsKeysSavePath) => super.noSuchMethod(
    Invocation.setter(#tlsKeysSavePath, _tlsKeysSavePath),
    returnValueForMissingStub: null,
  );

  @override
  set pathToCerts(String? _pathToCerts) => super.noSuchMethod(
    Invocation.setter(#pathToCerts, _pathToCerts),
    returnValueForMissingStub: null,
  );

  @override
  bool get enforceNamespace =>
      (super.noSuchMethod(
            Invocation.getter(#enforceNamespace),
            returnValue: false,
          )
          as bool);

  @override
  set enforceNamespace(bool? _enforceNamespace) => super.noSuchMethod(
    Invocation.setter(#enforceNamespace, _enforceNamespace),
    returnValueForMissingStub: null,
  );

  @override
  bool get fetchOfflineNotifications =>
      (super.noSuchMethod(
            Invocation.getter(#fetchOfflineNotifications),
            returnValue: false,
          )
          as bool);

  @override
  set fetchOfflineNotifications(bool? _fetchOfflineNotifications) =>
      super.noSuchMethod(
        Invocation.setter(
          #fetchOfflineNotifications,
          _fetchOfflineNotifications,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get useAtChops =>
      (super.noSuchMethod(Invocation.getter(#useAtChops), returnValue: false)
          as bool);

  @override
  set useAtChops(bool? _useAtChops) => super.noSuchMethod(
    Invocation.setter(#useAtChops, _useAtChops),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Version get atProtocolEmitted =>
      (super.noSuchMethod(
            Invocation.getter(#atProtocolEmitted),
            returnValue: _FakeVersion_9(
              this,
              Invocation.getter(#atProtocolEmitted),
            ),
          )
          as _i5.Version);

  @override
  set atProtocolEmitted(_i5.Version? _atProtocolEmitted) => super.noSuchMethod(
    Invocation.setter(#atProtocolEmitted, _atProtocolEmitted),
    returnValueForMissingStub: null,
  );

  @override
  _i6.AtClientParticulars get atClientParticulars =>
      (super.noSuchMethod(
            Invocation.getter(#atClientParticulars),
            returnValue: _FakeAtClientParticulars_10(
              this,
              Invocation.getter(#atClientParticulars),
            ),
          )
          as _i6.AtClientParticulars);

  @override
  set atClientParticulars(_i6.AtClientParticulars? _atClientParticulars) =>
      super.noSuchMethod(
        Invocation.setter(#atClientParticulars, _atClientParticulars),
        returnValueForMissingStub: null,
      );

  @override
  _i7.SigningAlgoType get signingAlgoType =>
      (super.noSuchMethod(
            Invocation.getter(#signingAlgoType),
            returnValue: _i7.SigningAlgoType.ecc_secp256r1,
          )
          as _i7.SigningAlgoType);

  @override
  set signingAlgoType(_i7.SigningAlgoType? _signingAlgoType) =>
      super.noSuchMethod(
        Invocation.setter(#signingAlgoType, _signingAlgoType),
        returnValueForMissingStub: null,
      );

  @override
  _i7.HashingAlgoType get hashingAlgoType =>
      (super.noSuchMethod(
            Invocation.getter(#hashingAlgoType),
            returnValue: _i7.HashingAlgoType.sha256,
          )
          as _i7.HashingAlgoType);

  @override
  set hashingAlgoType(_i7.HashingAlgoType? _hashingAlgoType) =>
      super.noSuchMethod(
        Invocation.setter(#hashingAlgoType, _hashingAlgoType),
        returnValueForMissingStub: null,
      );
}
