FROM dart:3.11.1@sha256:e3ea62cbe54470e5cc4c31cbc85693aa9b0b01723521baf0be634ea3597e1f5d AS buildimage

ENV REPO_DIR=/app/repo
ENV OUTPUT_DIR=/output

COPY . /app/repo

RUN set -eux ; \
    mkdir -p ${REPO_DIR} ${OUTPUT_DIR} ; \
    cd ${REPO_DIR}/packages/dart/sshnoports ; \
    dart pub get ; \
    dart compile exe bin/at_activate.dart -o ${OUTPUT_DIR}/at_activate ; \
    dart compile exe bin/npp_atserver.dart -o ${OUTPUT_DIR}/npp_atserver ; \
    dart compile exe bin/npp_file.dart -o ${OUTPUT_DIR}/npp_file ; \
    dart compile exe bin/npt.dart -o ${OUTPUT_DIR}/npt ; \
    dart compile exe bin/sshnp.dart -o ${OUTPUT_DIR}/sshnp ; \
    dart compile exe bin/sshnpd.dart -o ${OUTPUT_DIR}/sshnpd ; \
    dart compile exe bin/srv.dart -o ${OUTPUT_DIR}/srv ; \
    dart compile exe bin/srvd.dart -o ${OUTPUT_DIR}/srvd ; \
    dart compile exe bin/npevents.dart -o ${OUTPUT_DIR}/npevents ; \
    dart compile exe bin/npp.dart -o ${OUTPUT_DIR}/npp ; \
    dart compile exe bin/npp_client.dart -o ${OUTPUT_DIR}/npp_client ; \

FROM atsigncompany/noports_e2e_all_v2_base:latest

ENV USER=atsign
ENV HOMEDIR=/${USER}
ENV USER_ID=1024
ENV GROUP_ID=1024

COPY --from=buildimage /output/ /usr/local/bin/

USER ${USER}
WORKDIR ${HOMEDIR}

CMD sudo service ssh start
