#!/bin/bash

# shellcheck disable=SC2034
scriptName=$(basename -- "$0")
testToRun="$scriptName"

if test -z "$testScriptsDir"; then
  echo -e "    ${RED}check_env: testScriptsDir is not set${NC}" && exit 1
fi

source "$testScriptsDir/common/common_functions.include.sh"
source "$testScriptsDir/common/check_env.include.sh" || exit $?

daemonVersion="$1"
clientVersion="$2"

if [[ ${daemonVersion:0:1} == "c" ]]; then
  logInfo "    N/A  because c daemon isn't compatible with v4 clients"
  exit 50
fi

# Execute ssh-client 'dart', v4 daemon features, and it must be 'inline'
"$testScriptsDir/tests/shared/sshnp" "$1" "$2" "dart" "v4" "inline" "$testToRun"
