#!/bin/bash

# shellcheck disable=SC2034
scriptName=$(basename -- "$0")

if test -z "$testScriptsDir" ; then
  echo -e "    ${RED}check_env: testScriptsDir is not set${NC}" && exit 1
fi

# Execute ssh-client 'openssh', v4 daemon features, and print the ssh command
"$testScriptsDir/tests/shared/sshnp" "$1" "$2" "openssh" "v4" "print"
