#!/bin/bash

# shellcheck disable=SC2034
scriptName=$(basename -- "$0")

if test -z "$testScriptsDir" ; then
  echo -e "    ${RED}check_env: testScriptsDir is not set${NC}" && exit 1
fi

# Execute ssh-client 'openssh', v5 daemon features, and start the ssh session 'inline'
"$testScriptsDir/tests/shared/sshnp" "$1" "$2" "openssh" "v5" "inline"
