#!/bin/bash

# shellcheck disable=SC2034
scriptName=$(basename -- "$0")
testToRun="$scriptName"

if test -z "$testScriptsDir"; then
  echo -e "    ${RED}check_env: testScriptsDir is not set${NC}" && exit 1
fi

source "$testScriptsDir/common/common_functions.include.sh"
source "$testScriptsDir/common/check_env.include.sh" || exit $?

daemonVersion="$1"
clientVersion="$2"

if [[ ${daemonVersion:0:1} == "c" ]] && [[ $(versionIsLessThan "$clientVersion" "d:5.3.0") == "true" ]]; then
  logInfo "    N/A  because c daemon requires clients >= v5.3.0"
  exit 50
fi

# Execute ssh-client 'openssh', v5 daemon features, and start the ssh session 'inline'
"$testScriptsDir/tests/shared/sshnp" "$1" "$2" "openssh" "v5" "inline" "$testToRun"
