server {
    listen 80;

    # Landing page
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/html text/css application/javascript;

    location = / {
        try_files /index.html =404;
        add_header Cache-Control "no-cache";
    }

    # Proxy /cyd/ to the CYD flasher container
    location /cyd/ {
        proxy_pass         http://cyd-flasher/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    # Proxy /poe/ to the PoE flasher container
    location /poe/ {
        proxy_pass         http://poe-flasher/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }
}
