FROM debian:stable-20260623-slim@sha256:ee12ffb55625b99d62837a72f037d9b2f18fd0c787a89c2b9a4f09666c48776c AS buildimage

ENV URL="https://api.github.com/repos/atsign-foundation/noports/releases/latest"
ENV URLP="https://github.com/atsign-foundation/noports/releases/download"
ENV BUILD_DIR=/app
ENV OUTPUT_DIR=/output

ARG release=latest

RUN apt-get update && \
    apt-get install -y wget dpkg curl && \
    mkdir -p ${BUILD_DIR} ${OUTPUT_DIR} && \
    cd ${BUILD_DIR} && \
    case "$(dpkg --print-architecture)" in \
    amd64) ARCH="x64";; \
    armhf) ARCH="arm";; \
    arm64) ARCH="arm64";; \
    riscv64) ARCH="riscv64";; \
    esac && \
    if [ -z ${release} ] || [ "${release}" = 'latest' ]; then \
        LATEST_VERSION=$(curl --silent ${URL} | grep -Po '"tag_name": "\Kv.*?(?=")') && \
        VERSION=${LATEST_VERSION}; \
    else \
        VERSION=${release}; \
    fi && \
    wget "${URLP}/v${VERSION}/sshnp-linux-${ARCH}.tgz" && \
    tar -xvf sshnp-linux-${ARCH}.tgz && \
    rm sshnp-linux-${ARCH}.tgz && \
    cd sshnp && \
    mv -f at_activate install.sh np_admin npp_atserver npp_file npt srv srvd sshnp sshnpd npevents ${OUTPUT_DIR} || true

FROM atsigncompany/noports_e2e_all_base_runtime:latest@sha256:58b357f260a9332c4ae3902dff1e943eea012c29e9e91a815fe4421ff3412ff2 AS runtime

ENV USER=atsign
ENV HOMEDIR=/${USER}
ENV USER_ID=1024
ENV GROUP_ID=1024

COPY --from=buildimage /output/ /usr/local/bin/

USER ${USER}
WORKDIR ${HOMEDIR}

CMD sudo service ssh start
