FROM dart:3.12.2@sha256:a74253f8c88f341629a471b8706f8f7b9938207248d5f2ac6a8c2d2230b466c0 AS buildimage

ENV REPO_DIR=/app/repo
ENV OUTPUT_DIR=/output

COPY . /app/repo

RUN set -eux ; \
    mkdir -p ${REPO_DIR} ${OUTPUT_DIR} ; \
    cd ${REPO_DIR}/packages/dart/sshnoports ; \
    dart pub get ; \
    dart compile exe bin/at_activate.dart -o ${OUTPUT_DIR}/at_activate ; \
    dart compile exe bin/npp_atserver.dart -o ${OUTPUT_DIR}/npp_atserver ; \
    dart compile exe bin/npp_file.dart -o ${OUTPUT_DIR}/npp_file ; \
    dart compile exe bin/npt.dart -o ${OUTPUT_DIR}/npt ; \
    dart compile exe bin/sshnp.dart -o ${OUTPUT_DIR}/sshnp ; \
    dart compile exe bin/sshnpd.dart -o ${OUTPUT_DIR}/sshnpd ; \
    dart compile exe bin/srv.dart -o ${OUTPUT_DIR}/srv ; \
    dart compile exe bin/srvd.dart -o ${OUTPUT_DIR}/srvd ; \
    dart compile exe bin/npevents.dart -o ${OUTPUT_DIR}/npevents

FROM atsigncompany/noports_e2e_all_base_runtime:latest@sha256:2b4dd4e15c2befc65e5bc573932b961241d028bce71064dc266548b7ad96ca77 AS runtime

ENV USER=atsign
ENV HOMEDIR=/${USER}
ENV USER_ID=1024
ENV GROUP_ID=1024

COPY --from=buildimage /output/ /usr/local/bin/

USER ${USER}
WORKDIR ${HOMEDIR}

CMD sudo service ssh start
