FROM atsigncompany/cbuildimage:CMake-3.31.11@sha256:48ed145c886996c248e103254bc04c8b19da6b77f542c2593587e850016a7395 AS buildimage

ENV URL=https://github.com/atsign-foundation/noports.git
ENV REPO_DIR=/app/repo
ENV OUTPUT_DIR=/output

ARG branch=trunk

RUN set -eux ; \
    mkdir -p ${REPO_DIR} ${OUTPUT_DIR} ; \
    apt-get update ; \
    apt-get install -y git gcc ; \
    cd ${REPO_DIR} ; \
    git clone ${URL} . ; \
    git checkout ${branch} ; \
    cd ${REPO_DIR}/packages/c/sshnpd ; \
    cmake -S . -B build -DCMAKE_C_COMPILER=gcc -DBUILD_SHARED_LIBS=off -DCMAKE_C_FLAGS="-Wno-error -pthread" ; \
    cmake --build build ; \
    mv ./build/at_activate ${OUTPUT_DIR}/at_activate ; \
    mv ./build/sshnpd ${OUTPUT_DIR}/sshnpd ; \
    mv ./build/libsshnpd-lib.a ${OUTPUT_DIR}/libsshnpd-lib.a ; \
    cd ${REPO_DIR}/packages/c/srv ; \
    cmake -S . -B build -DCMAKE_C_COMPILER=gcc -DATAUTH_BUILD_EXECUTABLES=OFF -DBUILD_SHARED_LIBS=off -DCMAKE_C_FLAGS="-Wno-error -pthread" ; \
    cmake --build build ; \
    mv build/srv ${OUTPUT_DIR}/srv

FROM atsigncompany/noports_e2e_all_base_runtime:latest@sha256:ff6847e4af63cb5f38771e2d09a77842faf430a03fde799b37f6450c49a831a8 AS runtime

ENV USER=atsign
ENV HOMEDIR=/${USER}
ENV USER_ID=1024
ENV GROUP_ID=1024

COPY --from=buildimage /output/ /usr/local/bin/

USER ${USER}
WORKDIR ${HOMEDIR}

CMD sudo service ssh start
