FROM atsigncompany/cbuildimage:CMake-3.31.8@sha256:586a3c7ac9844148b0a8b3fea3e4728dfbf3c3430328051f56fb2865ca952056 AS buildimage

ENV REPO_DIR=/app/repo
ENV OUTPUT_DIR=/output

# WARNING: ensure that build context is set to the root of the repo
# e.g. `docker build -f tests/e2e_all/dockerfiles/Dockerfile.c.current -t noports-c:current .`
COPY . ${REPO_DIR}

RUN set -eux ; \
    mkdir -p ${REPO_DIR} ${OUTPUT_DIR} ; \
    apt-get update ; \
    apt-get install -y gcc ; \
    cd ${REPO_DIR}/packages/c/sshnpd ; \
    rm -rf build ; \
    cmake -S . -B build -DCMAKE_C_COMPILER=gcc -DBUILD_SHARED_LIBS=off -DCMAKE_C_FLAGS="-Wno-error -pthread" ; \
    cmake --build build ; \
    mv ./build/at_activate ${OUTPUT_DIR}/at_activate ; \
    mv ./build/sshnpd ${OUTPUT_DIR}/sshnpd ; \
    mv ./build/libsshnpd-lib.a ${OUTPUT_DIR}/libsshnpd-lib.a ; \
    cd ${REPO_DIR}/packages/c/srv ; \
    rm -rf build ; \
    cmake -S . -B build -DCMAKE_C_COMPILER=gcc -DATAUTH_BUILD_EXECUTABLES=OFF -DBUILD_SHARED_LIBS=off -DCMAKE_C_FLAGS="-Wno-error -pthread" ; \
    cmake --build build ; \
    mv build/srv ${OUTPUT_DIR}/srv


FROM atsigncompany/noports_e2e_all_base_runtime:latest@sha256:ac7aa4dac41182634924210b0251c31efa72bb10885b4bd68e981f6f56266842 AS runtime

ENV USER=atsign
ENV HOMEDIR=/${USER}
ENV USER_ID=1024
ENV GROUP_ID=1024

COPY --from=buildimage /output/ /usr/local/bin/

USER ${USER}
WORKDIR ${HOMEDIR}

CMD sudo service ssh start
