FROM atsigncompany/cbuildimage:CMake-3.31.11@sha256:48ed145c886996c248e103254bc04c8b19da6b77f542c2593587e850016a7395 AS buildimage

ENV REPO_DIR=/app/repo
ENV OUTPUT_DIR=/output

# WARNING: ensure that build context is set to the root of the repo
# e.g. `docker build -f tests/e2e_all/dockerfiles/Dockerfile.c.current -t noports-c:current .`
COPY . ${REPO_DIR}

RUN set -eux ; \
    mkdir -p ${REPO_DIR} ${OUTPUT_DIR} ; \
    apt-get update ; \
    apt-get install -y gcc ; \
    cd ${REPO_DIR}/packages/c/sshnpd ; \
    rm -rf build ; \
    cmake -S . -B build -DCMAKE_C_COMPILER=gcc -DBUILD_SHARED_LIBS=off -DCMAKE_C_FLAGS="-Wno-error -pthread" ; \
    cmake --build build ; \
    mv ./build/at_activate ${OUTPUT_DIR}/at_activate ; \
    mv ./build/sshnpd ${OUTPUT_DIR}/sshnpd ; \
    mv ./build/libsshnpd-lib.a ${OUTPUT_DIR}/libsshnpd-lib.a ; \
    cd ${REPO_DIR}/packages/c/srv ; \
    rm -rf build ; \
    cmake -S . -B build -DCMAKE_C_COMPILER=gcc -DATAUTH_BUILD_EXECUTABLES=OFF -DBUILD_SHARED_LIBS=off -DCMAKE_C_FLAGS="-Wno-error -pthread" ; \
    cmake --build build ; \
    mv build/srv ${OUTPUT_DIR}/srv


FROM atsigncompany/noports_e2e_all_base_runtime:latest@sha256:66709945f4fec378c3ff9d26ac554df9b0faf5787994e8f67e25d6d2e0e58e66 AS runtime

ENV USER=atsign
ENV HOMEDIR=/${USER}
ENV USER_ID=1024
ENV GROUP_ID=1024

COPY --from=buildimage /output/ /usr/local/bin/

USER ${USER}
WORKDIR ${HOMEDIR}

CMD sudo service ssh start
