FROM atsigncompany/cbuildimage:CMake-3.31.8@sha256:cb29d4124e9208a1d6f7277e56fd489b1e22461554a3bc31cb0561a8db19914e AS buildimage

ENV URL="https://api.github.com/repos/atsign-foundation/noports/releases/latest"
ENV URLP="https://github.com/atsign-foundation/noports/releases/download"
ENV BUILD_DIR=/app
ENV OUTPUT_DIR=/output

ARG release

RUN set -eux ; \
    apt-get update ; \
    apt-get install -y wget dpkg curl gcc ; \
    mkdir -p ${BUILD_DIR} ${OUTPUT_DIR} ; \
    cd ${BUILD_DIR} ; \
    case "$(dpkg --print-architecture)" in \
        amd64) ARCH="x64";; \
        armhf) ARCH="arm";; \
        arm64) ARCH="arm64";; \
        riscv64) ARCH="riscv64";; \
    esac ; \
    VERSION=${release} ; \
    EXT="tar.gz" ; \
    TARGZNAME="csshnpd-c${VERSION}.$EXT" ; \
    wget "${URLP}/c${VERSION}/${TARGZNAME}" ; \
    tar -xvf ${TARGZNAME} ; \
    cd csshnpd-c${VERSION} ; \
    cd sshnpd ; \
    cmake -S . -B build -DCMAKE_C_COMPILER=gcc -DBUILD_SHARED_LIBS=off -DCMAKE_C_FLAGS="-Wno-error -pthread" ; \
    cmake --build build ; \
    mv ./build/at_activate ${OUTPUT_DIR}/at_activate ; \
    mv ./build/sshnpd ${OUTPUT_DIR}/sshnpd ; \
    mv ./build/libsshnpd-lib.a ${OUTPUT_DIR}/libsshnpd-lib.a ; \
    cd ../srv ; \
    cmake -S . -B build -DCMAKE_C_COMPILER=gcc -DATAUTH_BUILD_EXECUTABLES=OFF -DBUILD_SHARED_LIBS=off -DCMAKE_C_FLAGS="-Wno-error -pthread" ; \
    cmake --build build ; \
    mv build/srv ${OUTPUT_DIR}/srv ;

FROM atsigncompany/noports_e2e_all_base_runtime:latest@sha256:6223c926c4e22b5fee4a93bef3cb4288633548e37afda634ffb10ffe9dd9b5e9 AS runtime

ENV USER=atsign
ENV HOMEDIR=/${USER}
ENV USER_ID=1024
ENV GROUP_ID=1024

COPY --from=buildimage /output/ /usr/local/bin/

USER ${USER}
WORKDIR ${HOMEDIR}

CMD sudo service ssh start
