FROM dart:3.13.3@sha256:7e57e61d97813dc57dd0801656ff4d5c5efafa47bae563a681571543ad30f199 AS buildimage

ENV REPO_DIR=/app/repo
ENV OUTPUT_DIR=/output

COPY . /app/repo

RUN set -eux ; \
    mkdir -p ${REPO_DIR} ${OUTPUT_DIR} ; \
    cd ${REPO_DIR}/packages/dart/sshnoports ; \
    dart pub get ; \
    dart compile exe bin/at_activate.dart -o ${OUTPUT_DIR}/at_activate ; \
    dart compile exe bin/npp_atserver.dart -o ${OUTPUT_DIR}/npp_atserver ; \
    dart compile exe bin/npp.dart -o ${OUTPUT_DIR}/npp ; \
    dart compile exe bin/npp_file.dart -o ${OUTPUT_DIR}/npp_file ; \
    dart compile exe bin/npt.dart -o ${OUTPUT_DIR}/npt ; \
    dart compile exe bin/sshnp.dart -o ${OUTPUT_DIR}/sshnp ; \
    dart compile exe bin/sshnpd.dart -o ${OUTPUT_DIR}/sshnpd ; \
    dart compile exe bin/srv.dart -o ${OUTPUT_DIR}/srv ; \
    dart compile exe bin/srvd.dart -o ${OUTPUT_DIR}/srvd ; \
    dart compile exe bin/npevents.dart -o ${OUTPUT_DIR}/npevents

FROM atsigncompany/noports_e2e_all_base_runtime:latest@sha256:1f83c03fa0267ab1d47875f9f83b10857ff57375046de97f2ad1369d39e49fc4 AS runtime

ENV USER=atsign
ENV HOMEDIR=/${USER}
ENV USER_ID=1024
ENV GROUP_ID=1024

COPY --from=buildimage /output/ /usr/local/bin/

USER ${USER}
WORKDIR ${HOMEDIR}

CMD sudo service ssh start
