FROM dart:3.11.5@sha256:03b628160f6906098352a6d9c97a147afaa28cf4af97cb588aa33655d6ec3125 AS buildimage

ENV REPO_DIR=/app/repo
ENV OUTPUT_DIR=/output

COPY . /app/repo

RUN set -eux ; \
    mkdir -p ${REPO_DIR} ${OUTPUT_DIR} ; \
    cd ${REPO_DIR}/packages/dart/sshnoports ; \
    dart pub get ; \
    dart compile exe bin/at_activate.dart -o ${OUTPUT_DIR}/at_activate ; \
    dart compile exe bin/npp_atserver.dart -o ${OUTPUT_DIR}/npp_atserver ; \
    dart compile exe bin/npp.dart -o ${OUTPUT_DIR}/npp ; \
    dart compile exe bin/npp_file.dart -o ${OUTPUT_DIR}/npp_file ; \
    dart compile exe bin/npt.dart -o ${OUTPUT_DIR}/npt ; \
    dart compile exe bin/sshnp.dart -o ${OUTPUT_DIR}/sshnp ; \
    dart compile exe bin/sshnpd.dart -o ${OUTPUT_DIR}/sshnpd ; \
    dart compile exe bin/srv.dart -o ${OUTPUT_DIR}/srv ; \
    dart compile exe bin/srvd.dart -o ${OUTPUT_DIR}/srvd ; \
    dart compile exe bin/npevents.dart -o ${OUTPUT_DIR}/npevents

FROM atsigncompany/noports_e2e_all_base_runtime:latest@sha256:96af983d6e0fcd45e704709f70943cbdc9c2f2e249c6757c6b7000ec3d81c4f2 AS runtime

# TODO: remove after base image is rebuilt with ca-certificates
USER root
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*

ENV USER=atsign
ENV HOMEDIR=/${USER}
ENV USER_ID=1024
ENV GROUP_ID=1024

COPY --from=buildimage /output/ /usr/local/bin/

USER ${USER}
WORKDIR ${HOMEDIR}

CMD sudo service ssh start
