server {
    listen 80;
    root   /usr/share/nginx/html;
    index  index.html;

    gzip            on;
    gzip_types      text/html text/css application/javascript application/json;
    gzip_min_length 1024;

    location ~* \.bin$ {
        add_header Content-Type              application/octet-stream;
        add_header Content-Disposition       "attachment";
        add_header Access-Control-Allow-Origin  "*";
        add_header Cache-Control             "no-cache";
    }

    location ~* \.json$ {
        add_header Content-Type             application/json;
        add_header Access-Control-Allow-Origin "*";
        add_header Cache-Control            "no-cache";
    }

    location / {
        try_files $uri $uri/ =404;
        add_header Cache-Control "no-cache";
    }
}
