// Mocks generated by Mockito 5.4.6 from annotations
// in npt_flutter/test/features/profile_list/view/profile_list_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:at_client_flutter/at_client_flutter.dart' as _i10;
import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:npt_flutter/features/back_up_key/cubit/backup_key_cubit.dart'
    as _i9;
import 'package:npt_flutter/features/favorite/favorite.dart' as _i12;
import 'package:npt_flutter/features/onboarding/cubit/onboarding_cubit.dart'
    as _i3;
import 'package:npt_flutter/features/profile/profile.dart' as _i2;
import 'package:npt_flutter/features/profile_list/cubit/sync_cubit.dart' as _i8;
import 'package:npt_flutter/features/profile_list/profile_list.dart' as _i4;
import 'package:npt_flutter/features/settings/settings.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileCacheState_0 extends _i1.SmartFake
    implements _i2.ProfileCacheState {
  _FakeProfileCacheState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileBloc_1 extends _i1.SmartFake implements _i2.ProfileBloc {
  _FakeProfileBloc_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOnboardingState_2 extends _i1.SmartFake
    implements _i3.OnboardingState {
  _FakeOnboardingState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileListBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileListBloc extends _i1.Mock implements _i4.ProfileListBloc {
  @override
  _i4.ProfileListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i5.dummyValue<_i4.ProfileListState>(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _i5.dummyValue<_i4.ProfileListState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i4.ProfileListState);

  @override
  _i6.Stream<_i4.ProfileListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.ProfileListState>.empty(),
            returnValueForMissingStub: _i6.Stream<_i4.ProfileListState>.empty(),
          )
          as _i6.Stream<_i4.ProfileListState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void clearAll() => super.noSuchMethod(
    Invocation.method(#clearAll, []),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i4.ProfileListEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.ProfileListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void add(_i4.ProfileListEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i4.ProfileListEvent>(
    _i7.EventHandler<E, _i4.ProfileListState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i7.Transition<_i4.ProfileListEvent, _i4.ProfileListState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i4.ProfileListEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i7.Change<_i4.ProfileListState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ProfileCacheCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileCacheCubit extends _i1.Mock implements _i2.ProfileCacheCubit {
  @override
  _i2.ProfileCacheState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeProfileCacheState_0(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeProfileCacheState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.ProfileCacheState);

  @override
  _i6.Stream<_i2.ProfileCacheState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i2.ProfileCacheState>.empty(),
            returnValueForMissingStub:
                _i6.Stream<_i2.ProfileCacheState>.empty(),
          )
          as _i6.Stream<_i2.ProfileCacheState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.ProfileBloc getProfileBloc(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileBloc, [uuid]),
            returnValue: _FakeProfileBloc_1(
              this,
              Invocation.method(#getProfileBloc, [uuid]),
            ),
            returnValueForMissingStub: _FakeProfileBloc_1(
              this,
              Invocation.method(#getProfileBloc, [uuid]),
            ),
          )
          as _i2.ProfileBloc);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.ProfileCacheState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i2.ProfileCacheState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [SyncCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncCubit extends _i1.Mock implements _i8.SyncCubit {
  @override
  bool get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Stream<bool> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<bool>.empty(),
            returnValueForMissingStub: _i6.Stream<bool>.empty(),
          )
          as _i6.Stream<bool>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<void> checkSync() =>
      (super.noSuchMethod(
            Invocation.method(#checkSync, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void emit(bool? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<bool>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [ProfileBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileBloc extends _i1.Mock implements _i2.ProfileBloc {
  @override
  String get uuid =>
      (super.noSuchMethod(
            Invocation.getter(#uuid),
            returnValue: _i5.dummyValue<String>(this, Invocation.getter(#uuid)),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#uuid),
            ),
          )
          as String);

  @override
  _i2.ProfileState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i5.dummyValue<_i2.ProfileState>(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _i5.dummyValue<_i2.ProfileState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.ProfileState);

  @override
  _i6.Stream<_i2.ProfileState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i2.ProfileState>.empty(),
            returnValueForMissingStub: _i6.Stream<_i2.ProfileState>.empty(),
          )
          as _i6.Stream<_i2.ProfileState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void onEvent(_i2.ProfileEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.ProfileState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void add(_i2.ProfileEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i2.ProfileEvent>(
    _i7.EventHandler<E, _i2.ProfileState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i7.Transition<_i2.ProfileEvent, _i2.ProfileState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i2.ProfileEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i7.Change<_i2.ProfileState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BackupKeyCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupKeyCubit extends _i1.Mock implements _i9.BackupKeyCubit {
  @override
  bool get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Stream<bool> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<bool>.empty(),
            returnValueForMissingStub: _i6.Stream<bool>.empty(),
          )
          as _i6.Stream<bool>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<bool> getBackupKeyStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getBackupKeyStatus, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> putBackupKeyStatus(bool? status) =>
      (super.noSuchMethod(
            Invocation.method(#putBackupKeyStatus, [status]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void setBackupKeyStatus(bool? status) => super.noSuchMethod(
    Invocation.method(#setBackupKeyStatus, [status]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> backUpKeys({bool? popDialog = true}) =>
      (super.noSuchMethod(
            Invocation.method(#backUpKeys, [], {#popDialog: popDialog}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void emit(bool? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<bool>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [OnboardingCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingCubit extends _i1.Mock implements _i3.OnboardingCubit {
  @override
  _i3.OnboardingState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeOnboardingState_2(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeOnboardingState_2(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.OnboardingState);

  @override
  _i6.Stream<_i3.OnboardingState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i3.OnboardingState>.empty(),
            returnValueForMissingStub: _i6.Stream<_i3.OnboardingState>.empty(),
          )
          as _i6.Stream<_i3.OnboardingState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setRootDomain(String? rootDomain) => super.noSuchMethod(
    Invocation.method(#setRootDomain, [rootDomain]),
    returnValueForMissingStub: null,
  );

  @override
  String getRootDomain() =>
      (super.noSuchMethod(
            Invocation.method(#getRootDomain, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getRootDomain, []),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.method(#getRootDomain, []),
            ),
          )
          as String);

  @override
  void setAtsign(_i10.Atsign? atsign) => super.noSuchMethod(
    Invocation.method(#setAtsign, [atsign]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Atsign getAtsign() =>
      (super.noSuchMethod(
            Invocation.method(#getAtsign, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getAtsign, []),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.method(#getAtsign, []),
            ),
          )
          as _i10.Atsign);

  @override
  void setStatus(_i3.OnboardingStatus? status) => super.noSuchMethod(
    Invocation.method(#setStatus, [status]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.OnboardingStatus getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i3.OnboardingStatus.onboarded,
            returnValueForMissingStub: _i3.OnboardingStatus.onboarded,
          )
          as _i3.OnboardingStatus);

  @override
  void setState({
    _i10.Atsign? atsign,
    _i3.OnboardingStatus? status,
    String? rootDomain,
  }) => super.noSuchMethod(
    Invocation.method(#setState, [], {
      #atsign: atsign,
      #status: status,
      #rootDomain: rootDomain,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.OnboardingState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i3.OnboardingState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [SettingsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsBloc extends _i1.Mock implements _i11.SettingsBloc {
  @override
  _i11.SettingsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i5.dummyValue<_i11.SettingsState>(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _i5.dummyValue<_i11.SettingsState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i11.SettingsState);

  @override
  _i6.Stream<_i11.SettingsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i11.SettingsState>.empty(),
            returnValueForMissingStub: _i6.Stream<_i11.SettingsState>.empty(),
          )
          as _i6.Stream<_i11.SettingsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i11.SettingsEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i11.SettingsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void add(_i11.SettingsEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i11.SettingsEvent>(
    _i7.EventHandler<E, _i11.SettingsState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i7.Transition<_i11.SettingsEvent, _i11.SettingsState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i11.SettingsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i7.Change<_i11.SettingsState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ProfilesSelectedCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfilesSelectedCubit extends _i1.Mock
    implements _i4.ProfilesSelectedCubit {
  @override
  _i4.ProfilesSelectedState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i5.dummyValue<_i4.ProfilesSelectedState>(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _i5
                .dummyValue<_i4.ProfilesSelectedState>(
                  this,
                  Invocation.getter(#state),
                ),
          )
          as _i4.ProfilesSelectedState);

  @override
  _i6.Stream<_i4.ProfilesSelectedState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.ProfilesSelectedState>.empty(),
            returnValueForMissingStub:
                _i6.Stream<_i4.ProfilesSelectedState>.empty(),
          )
          as _i6.Stream<_i4.ProfilesSelectedState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void select(String? uuid) => super.noSuchMethod(
    Invocation.method(#select, [uuid]),
    returnValueForMissingStub: null,
  );

  @override
  void deselect(String? uuid) => super.noSuchMethod(
    Invocation.method(#deselect, [uuid]),
    returnValueForMissingStub: null,
  );

  @override
  void deselectAll() => super.noSuchMethod(
    Invocation.method(#deselectAll, []),
    returnValueForMissingStub: null,
  );

  @override
  void selectAll() => super.noSuchMethod(
    Invocation.method(#selectAll, []),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.ProfilesSelectedState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i4.ProfilesSelectedState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [FavoriteBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteBloc extends _i1.Mock implements _i12.FavoriteBloc {
  @override
  _i12.FavoritesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i5.dummyValue<_i12.FavoritesState>(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _i5.dummyValue<_i12.FavoritesState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i12.FavoritesState);

  @override
  _i6.Stream<_i12.FavoritesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i12.FavoritesState>.empty(),
            returnValueForMissingStub: _i6.Stream<_i12.FavoritesState>.empty(),
          )
          as _i6.Stream<_i12.FavoritesState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void clearAll() => super.noSuchMethod(
    Invocation.method(#clearAll, []),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i12.FavoriteEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i12.FavoritesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void add(_i12.FavoriteEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i12.FavoriteEvent>(
    _i7.EventHandler<E, _i12.FavoritesState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i7.Transition<_i12.FavoriteEvent, _i12.FavoritesState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i12.FavoriteEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i7.Change<_i12.FavoritesState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
