version: "3.8"

services:
  image-manual-local:
    build:
      context: ../../../
      dockerfile: ./tests/end2end_tests/image/Dockerfile
      target: manual-local
    image: atsigncompany/sshnp-e2e-manual:local
    deploy:
      mode: replicated
      replicas: 0
  container-sshnpd:
    image: atsigncompany/sshnp-e2e-manual:local
    container_name: manual_local_sshnpd
    volumes:
      - ../../../../contexts/sshnpd/.atsign/keys/:/atsign/.atsign/keys/ # mount keys
    networks:
      - sshnpd
    depends_on:
      - image-manual-local
  container-sshnp:
    image: atsigncompany/sshnp-e2e-manual:local
    container_name: manual_local_sshnp
    volumes:
      - ../../../../contexts/sshnp/.atsign/keys/:/atsign/.atsign/keys/ # mount keys
    networks:
      - sshnp
    depends_on:
      - image-manual-local
  # container-srvd:
  #   image: atsigncompany/sshnp-e2e-manual:local
  #   container_name: manual_local_srvd
  #   volumes:
  #     - ../../../../contexts/srvd/.atsign/keys/:/atsign/.atsign/keys/ # mount keys
  #   network_mode: host
  #   depends_on:
  #     - image-manual-local

networks:
  sshnpd:
    name: atsigncompany/sshnp-e2e-manual-network-sshnpd
    driver: bridge
  sshnp:
    name: atsigncompany/sshnp-e2e-manual-network-sshnp
    driver: bridge
