name: C_Release_Automation

on:
  push:
    tags:
      - "c*.*.*"
  workflow_dispatch:

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  verify_tags:
    permissions:
      contents: write # Needed to create workflow branch
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Create action branch
        run: |
          git config --global user.name 'Atsign Robot'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git checkout -b c_release-${{github.run_number}}
      - name:
          Ensure pubspec.yaml matches git ref (if current git ref is a version
          tag)
        shell: bash
        if: startsWith(github.ref, 'refs/tags/c')
        working-directory: ./packages/c/sshnpd/include/sshnpd/
        run: |
          REF=${{ github.ref }}
          VER=${REF:11}
          sed -i "0,/#define SSHNPD_VERSION/{s/#define SSHNPD_VERSION \(.*\)/#DEFINE SSHNPD_VERSION "${VER}"/}" version.h
          if [ "$(git status --porcelain)" ]; then
            git add .
            git commit -m 'ci: Updated version to tag'
          fi
      - name: Push changes to branch
        run: git push --set-upstream origin c_release-${{github.run_number}}

  zig_build:
    needs: [verify_tags]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/c/sshnpd
    strategy:
      fail-fast: false
      matrix:
        include:
          - output-name: sshnpd-macos-x64
            target: x86_64-macos
            system_name: Darwin
            system_processor: x86_64
            c_flags: "-Wno-error"
            exe_linker_flags: ""
          - output-name: sshnpd-macos-arm64
            target: aarch64-macos
            system_name: Darwin
            system_processor: arm64
            c_flags: "-Wno-error"
            exe_linker_flags: ""
          - output-name: sshnpd-linux-x64
            target: x86_64-linux-gnu.2.17
            system_name: Linux
            system_processor: x86_64
            c_flags: "-Wno-error -pthread"
            exe_linker_flags: "-pthread -lrt"
          - output-name: sshnpd-linux-x64-musl
            target: x86_64-linux-musl
            system_name: Linux
            system_processor: x86_64
            c_flags: "-Wno-error"
            exe_linker_flags: "-static"
          - output-name: sshnpd-linux-arm64
            target: aarch64-linux-gnu.2.17
            system_name: Linux
            system_processor: aarch64
            c_flags: "-Wno-error -pthread"
            exe_linker_flags: "-pthread -lrt"
          - output-name: sshnpd-linux-arm64-musl
            target: aarch64-linux-musl
            system_name: Linux
            system_processor: aarch64
            c_flags: "-Wno-error"
            exe_linker_flags: "-static"
          - output-name: sshnpd-linux-arm
            target: arm-linux-gnueabihf.2.17
            system_name: Linux
            system_processor: armv7l
            c_flags: "-Wno-error -pthread"
            exe_linker_flags: "-pthread -lrt"
          - output-name: sshnpd-linux-armv-musl
            target: arm-linux-musleabihf
            system_name: Linux
            system_processor: armv7l
            c_flags: "-Wno-error"
            exe_linker_flags: "-static"
          - output-name: sshnpd-linux-riscv64
            target: riscv64-linux-gnu.2.27
            system_name: Linux
            system_processor: riscv64
            c_flags: "-Wno-error -pthread"
            exe_linker_flags: "-pthread -lrt"
          - output-name: lsshnpd-inux-riscv64-musl
            target: riscv64-linux-musl
            system_name: Linux
            system_processor: riscv64
            c_flags: "-Wno-error"
            exe_linker_flags: "-static"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: c_release-${{github.run_number}}
      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
        # Pin cmake to <4.0.0
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
        with:
          cmake-version: "3.31.11"
      - name: Compile binaries
        run: |
          CC="zig cc -target ${{ matrix.target }}" \
          cmake \
            -B build \
            -DCMAKE_SYSTEM_NAME="${{ matrix.system_name }}" \
            -DCMAKE_SYSTEM_PROCESSOR="${{ matrix.system_processor }}" \
            -DCMAKE_C_FLAGS="${{ matrix.c_flags }}" \
            -DCMAKE_EXE_LINKER_FLAGS="${{ matrix.exe_linker_flags }}" \
            -DCMAKE_C_CREATE_STATIC_LIBRARY="zig ar qc <TARGET> <LINK_FLAGS> <OBJECTS>; zig ranlib <TARGET>" \
            -DBUILD_SHARED_LIBS=OFF \
            -DBUILD_TESTS=OFF
          cmake --build build
          mkdir tarball
          mv build/sshnpd .
          mv build/at_activate .
      - name: Zip the build (MacOS only)
        if: ${{ matrix.system_name == 'Darwin' }}
        run: zip tarball/${{ matrix.output-name }}.zip sshnpd at_activate
      - name: Archive to tgz (Linux only)
        if: ${{ matrix.system_name == 'Linux' }}
        run: tar -cvzf tarball/${{ matrix.output-name }}.tgz sshnpd at_activate
      - name: Upload archives
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.output-name }}_${{ github.ref_name
            }}-${{github.run_number}}-${{github.run_attempt}}
          path: ./packages/c/sshnpd/tarball
          if-no-files-found: error

  source_tarball:
    needs: [verify_tags]
    name: Generate source tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: c_release-${{github.run_number}}
        # Pin cmake to <4.0.0
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
        with:
          cmake-version: "3.31.11"
      - name: Create tarball
        working-directory: ./packages/c
        run: |
          cmake --workflow --preset package-source
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: csshnpd-src-${{github.ref_name}}-${{github.run_number}}-${{github.run_attempt}}
          path: ./packages/c/build/release-static/csshnpd-${{ github.ref_name }}.tar.gz

  github-release:
    if: startsWith(github.ref, 'refs/tags/c')
    name: >-
      Upload artifacts and generate checksums for provenance
    needs: [zig_build, source_tarball]
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    permissions:
      contents: write # IMPORTANT: mandatory for making GitHub Releases
      id-token: write # IMPORTANT: mandatory for sigstore
      attestations: write
    steps:
      - name: Get lockfile
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          sparse-checkout: |
            packages/c/conan.lock
          sparse-checkout-cone-mode: false
      - name: Download all the tarballs
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: tarballs/
      - name: Move packages for signing
        run: |
          cd tarballs
          echo "Before:"
          ls -latrR *
          shopt -s nullglob
          packages=( */*.tgz */*.tar.gz */*.zip )
          if ((${#packages[@]})); then
            mv "${packages[@]}" .
          fi
          rm -Rf -- */
          echo "After:"
          ls -latrR *
      - name: Generate SBOM
        uses: sbomify/github-action@fc7f05256cca65c26c8010da5faf3203e9477e5c # v26.9.0
        env:
          TOKEN: ${{ secrets.SBOMIFY_TOKEN }}
          COMPONENT_ID: 'Y6pppn8rC4'
          LOCK_FILE: './packages/c/conan.lock'
          COMPONENT_NAME: 'csshnpd'
          COMPONENT_VERSION: ${{github.ref_name}}-gha${{github.run_number}}
          OUTPUT_FILE: 'tarballs/csshnpd-${{github.ref_name}}-sbom.cdx.json'
          AUGMENT: true
          ENRICH: true
          UPLOAD: true
      - name: Generate SHA256 checksums
        working-directory: tarballs
        run: sha256sum * > checksums.txt
      - name: Upload artifacts to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload '${{ github.ref_name }}' tarballs/** --repo '${{
          github.repository }}'
      - id: hash
        name: Pass artifact hashes for SLSA provenance
        working-directory: tarballs
        run: |
          echo "hashes=$(cat checksums.txt | base64 -w0)" >> "$GITHUB_OUTPUT"
      - name: GitHub attestation
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        with:
          subject-path: "tarballs/**"

  provenance:
    needs: [github-release]
    permissions:
      actions: read # Needed for detection of GitHub Actions environment.
      id-token: write # Needed for provenance signing and ID
      contents: write # Needed for release uploads
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0 # 5a775b367a56d5bd118a224a811bba288150a563
    with:
      base64-subjects: "${{ needs.github-release.outputs.hashes }}"
      upload-assets: true
