name: C_Release_Automation

on:
  push:
    tags:
      - "c*.*.*"
  workflow_dispatch:
    inputs:
      native_build_only:
        description: "Run non-dockerx builds only"
        required: true
        default: false
        type: boolean

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  verify_tags:
    permissions:
      contents: write # Needed to create workflow branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Create action branch
        run: |
          git config --global user.name 'Atsign Robot'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git checkout -b c_release-${{github.run_number}}
      - name:
          Ensure pubspec.yaml matches git ref (if current git ref is a version
          tag)
        shell: bash
        if: startsWith(github.ref, 'refs/tags/c')
        working-directory: ./packages/c/sshnpd/include/sshnpd/
        run: |
          REF=${{ github.ref }}
          VER=${REF:11}
          sed -i "0,/#define SSHNPD_VERSION/{s/#define SSHNPD_VERSION \(.*\)/#DEFINE SSHNPD_VERSION "${VER}"/}" version.h
          if [ "$(git status --porcelain)" ]; then
            git add .
            git commit -m 'ci: Updated version to tag'
          fi
      - name: Push changes to branch
        run: git push --set-upstream origin c_release-${{github.run_number}}

  native_build:
    needs: [verify_tags]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./packages/c/sshnpd
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15-intel
            output-name: sshnpd-macos-x64
            ext: ""
            bundle: "shell"
            compiler: "clang"
            flags: "-Wno-error -pthread"
          - os: macos-latest
            output-name: sshnpd-macos-arm64
            ext: ""
            bundle: "shell"
            compiler: "clang"
            flags: "-Wno-error -pthread"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: c_release-${{github.run_number}}

        # Pin cmake to <4.0.0
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
        with:
          cmake-version: "3.31.11"
      - name: Compile binaries
        run: |
          cmake -B build -S . -DBUILD_SHARED_LIBS=off -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_C_FLAGS="${{matrix.flags}}"
          cmake --build build
          mkdir tarball
          mv build/sshnpd .
          mv build/at_activate .
      - name: Zip the build
        run: zip tarball/${{ matrix.output-name }}.zip sshnpd at_activate
      - name: Upload archives
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.output-name }}_${{ matrix.compiler
            }}-${{  github.ref_name
            }}-${{github.run_number}}-${{github.run_attempt}}
          path: ./packages/c/sshnpd/tarball
          if-no-files-found: error

  docker_builds:
    needs: [verify_tags]
    if: ${{ ! inputs.native_build_only }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./packages/c
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
            output-name: sshnpd-linux-x64
            dockerfile: Dockerfile.package
          - os: ubuntu-latest
            platform: linux/amd64
            output-name: sshnpd-linux-x64-musl
            dockerfile: Dockerfile.musl
          - os: ubuntu-24.04-arm
            platform: linux/arm64
            output-name: sshnpd-linux-arm64
            dockerfile: Dockerfile.package
          - os: ubuntu-24.04-arm
            platform: linux/arm64
            output-name: sshnpd-linux-arm64-musl
            dockerfile: Dockerfile.musl
          - os: ubuntu-24.04-arm
            platform: linux/arm/v7
            output-name: sshnpd-linux-arm-musl
            dockerfile: Dockerfile.musl
          - os: ubuntu-24.04-arm
            platform: linux/riscv64
            output-name: sshnpd-linux-riscv64-musl
            dockerfile: Dockerfile.musl
    ## 20240806: Clang and CMake that we use aren't packaged for
    ## armv7 or riscv64 (also no Debian 11 for RISC-V)
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: c_release-${{github.run_number}}
      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - name: Build tarballs in Docker
        run: |
          docker buildx build -t atsigncompany/sshnpdc \
          -f sshnpd/tools/${{ matrix.dockerfile }} \
          --platform ${{ matrix.platform }} -o type=tar,dest=bins.tar .
          mkdir tarballs
          tar -xvf bins.tar -C tarballs
      - name: Upload tarballs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{
            matrix.output-name  }}-${{  github.ref_name  }}-${{  github.run_number
            }}-${{  github.run_attempt  }}
          path: ./packages/c/tarballs/${{ matrix.output-name }}.tgz

  source_tarball:
    needs: [verify_tags]
    name: Generate source tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: c_release-${{github.run_number}}
        # Pin cmake to <4.0.0
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
        with:
          cmake-version: "3.31.11"
      - name: Create tarball
        working-directory: ./packages/c
        run: |
          cmake --workflow --preset package-source
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: csshnpd-src-${{github.ref_name}}-${{github.run_number}}-${{github.run_attempt}}
          path: ./packages/c/build/release-static/csshnpd-${{ github.ref_name }}.tar.gz

  github-release:
    if: startsWith(github.ref, 'refs/tags/c')
    name: >-
      Upload artifacts and generate checksums for provenance
    needs: [native_build, docker_builds, source_tarball]
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    permissions:
      contents: write # IMPORTANT: mandatory for making GitHub Releases
      id-token: write # IMPORTANT: mandatory for sigstore
      attestations: write
    steps:
      - name: Get lockfile
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          sparse-checkout: |
            packages/c/conan.lock
          sparse-checkout-cone-mode: false
      - name: Download all the tarballs
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: tarballs/
      - name: Move packages for signing
        run: |
          cd tarballs
          echo "Before:"
          ls -latrR *
          mv */*.tgz .
          mv */*.tar.gz .
          mv */*.zip .
          rm -Rf -- */
          echo "After:"
          ls -latrR *
      - name: Generate SBOM
        uses: sbomify/github-action@ac8b0d423c90447f3011ef8ab5f9ff2e854c6931 # v26.2.0
        env:
          TOKEN: ${{ secrets.SBOMIFY_TOKEN }}
          COMPONENT_ID: 'Y6pppn8rC4'
          LOCK_FILE: './packages/c/conan.lock'
          COMPONENT_NAME: 'csshnpd'
          COMPONENT_VERSION: ${{github.ref_name}}-gha${{github.run_number}}
          OUTPUT_FILE: 'tarballs/csshnpd-${{github.ref_name}}-sbom.cdx.json'
          AUGMENT: true
          ENRICH: true
          UPLOAD: true
      - name: Generate SHA256 checksums
        working-directory: tarballs
        run: sha256sum * > checksums.txt
      - name: Upload artifacts to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload '${{ github.ref_name }}' tarballs/** --repo '${{
          github.repository }}'
      - id: hash
        name: Pass artifact hashes for SLSA provenance
        working-directory: tarballs
        run: |
          echo "hashes=$(cat checksums.txt | base64 -w0)" >> "$GITHUB_OUTPUT"
      - name: GitHub attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: "tarballs/**"

  provenance:
    needs: [github-release]
    permissions:
      actions: read # Needed for detection of GitHub Actions environment.
      id-token: write # Needed for provenance signing and ID
      contents: write # Needed for release uploads
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0 # 5a775b367a56d5bd118a224a811bba288150a563
    with:
      base64-subjects: "${{ needs.github-release.outputs.hashes }}"
      upload-assets: true
