name: C Unit Tests

on:
  workflow_dispatch:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  unit-tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: atsdk Unit CTest
        working-directory: packages/c
        run: |
          cmake -S . -B build -DSSHNPD_BUILD_TESTS=ON
          cmake --build build
          ctest --test-dir build/sshnpd/tests --output-on-failure --timeout 2
