name: C Unit Tests

on:
  workflow_dispatch:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  unit-tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

        # Pin cmake to <4.0.0
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
        with:
          cmake-version: "3.31.11"

      - name: sshnpd Unit CTest
        working-directory: packages/c
        run: |
          cmake -S . -B build -DSSHNPD_BUILD_TESTS=ON
          cmake --build build
          ctest --test-dir build/sshnpd/tests --output-on-failure --timeout 2
