name: Cppcheck
on:
  workflow_dispatch:
  push:
    branches: [trunk]
    paths:
      - '/packages/c/**'
  pull_request:
    branches: [trunk]
    paths:
      - '/packages/c/**'

permissions:
  contents: read

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/c
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Cppcheck
        run: |
          sudo apt install -y cppcheck
          cppcheck .
