name: Cppcheck
on:
  workflow_dispatch:
  push:
    branches: [trunk]
    paths:
      - '/packages/c/**'
  pull_request:
    branches: [trunk]
    paths:
      - '/packages/c/**'

permissions:
  contents: read

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/c
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Cppcheck
        run: |
          sudo apt install -y cppcheck
          cppcheck .
