name: Cppcheck
on:
  workflow_dispatch:
  push:
    branches: [trunk]
    paths:
      - '/packages/c/**'
  pull_request:
    branches: [trunk]
    paths:
      - '/packages/c/**'

permissions:
  contents: read

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/c
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Cppcheck
        run: |
          sudo apt install -y cppcheck
          cppcheck .
