name: Cppcheck
on:
  workflow_dispatch:
  push:
    branches: [trunk]
    paths:
      - '/packages/c/**'
  pull_request:
    branches: [trunk]
    paths:
      - '/packages/c/**'

permissions:
  contents: read

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/c
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Cppcheck
        run: |
          sudo apt install -y cppcheck
          cppcheck .
