name: dockerhub_promote_to_latest

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the image to promote"
        required: true
        default: sshnpd
        type: choice
        options:
          - sshnpd
          - activate_sshnpd

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - name: Login to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Extract version for docker tag
      - name: Get version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Promote image to latest
        run: docker buildx imagetools create -t atsigncompany/${{ inputs.name }}:latest atsigncompany/${{ inputs.name }}:release-${{ env.VERSION }}
