name: e2e_all

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - trunk

  pull_request:
    paths-ignore:
      - "docs/**"
    branches:
      - trunk
      - release-v*.*.*

jobs:
  e2e_all:
    # Don't run on PRs from a fork or Dependabot as the secrets aren't available
    if:
      ${{ github.event.pull_request.head.repo.fork == false && github.actor !=
      'dependabot[bot]'}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup dart
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.7.1
      - name: Set stuff up 
        run: |
          mkdir -p /tmp/e2e_all
          mkdir -p ~/.atsign/keys/
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > ~/.atsign/keys/@8incanteater_key.atKeys
          echo "${{ secrets.ATKEYS_8485WEALTHY51 }}" > ~/.atsign/keys/@8485wealthy51_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > ~/.atsign/keys/@8052simple_key.atKeys
          echo "${{ secrets.ATKEYS_829SNOWSHOEING }}" > ~/.atsign/keys/@829snowshoeing_key.atKeys
      - name: Install expect
        run: |
          sudo apt-get update
          sudo apt-get install -y expect
      - name: Execute tests/e2e_all/scripts/main.sh
        run: |
          echo "Test started at: $(date)"
          start_time=$(date +%s)
          tests/e2e_all/scripts/main.sh @8052simple @829snowshoeing @rv_eu -p
          test_exit_code=$?
          end_time=$(date +%s)
          echo "Test finished at: $(date)"
          echo "Total execution time: $((end_time - start_time)) seconds"
          exit $test_exit_code
      - name: Zip /tmp/e2e_all
        run: |
          zip -r tmp_e2e_all_artifacts.zip /tmp/e2e_all
      - name: Upload /tmp/e2e_all as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: tmp_e2e_all_artifacts
          path: tmp_e2e_all_artifacts.zip 
