name: Gitbook Review
on:
  push:
    branches:
      - gitbook

permissions:
  contents: read

jobs:
  create-pull-request:
    env:
      branch: gitbook

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Authenticate GitHub CLI
        run: |
          echo -e ${{ secrets.MY_GITHUB_TOKEN }} | gh auth login --with-token 

      - name: Create Pull Request
        run: |
          gh pr create \
            --base 'trunk' \
            --head 'gitbook' \
            --reviewer 'xavierchanth' \
            --title 'docs(automated): Update docs from Gitbook' \
            --body 'Sync Gitbook docs branch to trunk' || \
          echo "Already created?";
