name: Multibuild

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  verify_tags:
    permissions:
      contents: write # Needed to create workflow branch
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Create action branch
        run: |
          git config --global user.name 'Atsign Robot'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git checkout -b multibuild-${{github.run_number}}
      - name:
          Ensure pubspec.yaml matches git ref (if current git ref is a version
          tag)
        shell: bash
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: ./packages/dart/sshnoports
        run: |
          REF=${{ github.ref }}
          VER=${REF:11}
          sed -i "0,/version:/{s/version: \(.*\)/version: "${VER}"/}" pubspec.yaml
          if [ "$(git status --porcelain)" ]; then
            git add .
            git commit -m 'ci: Updated version to tag'
          fi
      - name: Push changes to branch
        run: git push --set-upstream origin multibuild-${{github.run_number}}
      - name: Extract Version from pubspec.yaml
        id: extract_version
        working-directory: ./packages/dart/sshnoports
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | sed 's/version: //' | cut -d'+' -f1 | xargs)
          echo "Detected version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  main_build:
    needs: verify_tags
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./packages/dart/sshnoports
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            output-name: sshnp-linux-x64
            arch: "amd64"
            cross: ""
            ext: ""
            bundle: "shell"
            platform: "linux"
          - os: ubuntu-24.04-arm
            output-name: sshnp-linux-arm
            arch: "arm7"
            cross: "--target-os=linux --target-arch=arm"
            ext: ""
            bundle: "shell"
            platform: "linux"
          - os: ubuntu-24.04-arm
            output-name: sshnp-linux-arm64
            arch: "arm64"
            cross: ""
            ext: ""
            bundle: "shell"
            platform: "linux"
          - os: ubuntu-24.04-arm
            output-name: sshnp-linux-riscv64
            arch: "riscv64"
            cross: "--target-os=linux --target-arch=riscv64"
            ext: ""
            bundle: "shell"
            platform: "linux"
          - os: macos-15-intel
            output-name: sshnp-macos-x64
            arch: "amd64"
            cross: ""
            ext: ""
            bundle: "shell"
            platform: "macos"
          - os: macos-latest
            output-name: sshnp-macos-arm64
            arch: "arm64"
            cross: ""
            ext: ""
            bundle: "shell"
            platform: "macos"
          - os: windows-signer
            output-name: sshnp-windows-x64
            arch: "amd64"
            cross: ""
            ext: ".exe"
            bundle: "windows"
            platform: "windows"
    env:
      ARCH: ${{ matrix.arch }}
      BINS: "at_activate noports npevents npp npp_atserver npp_file npt srv sshnp sshnpd"
      CROSS: ${{ matrix.cross }}
      EXT: ${{ matrix.ext }}
      VERSION: ${{ needs.verify_tags.outputs.version }}
    steps:
      - name: Checkout multibuild branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: multibuild-${{github.run_number}}
      - name: Setup dart
        uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1.7.2
      - name: Setup Go (Linux only)
        if: ${{ matrix.platform == 'linux' }} # Only needed for nfpm packaging
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '1.25.6'
          cache: false
      - name: Set up QEMU (Linux riscv64 and armv7 only)
        if: ${{ matrix.arch == 'riscv64' || matrix.arch == 'armv7' }}
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
        with:
          platforms: ${{ matrix.arch }}
      - name: Create directories
        run: |
          mkdir sshnp
          mkdir tarball
      - name: Create debug directory (Non-Windows)
        if: ${{ matrix.platform != 'windows' }}
        run: mkdir sshnp/debug
      - name: Compile core binaries
        run: |
          dart pub get --enforce-lockfile
          dart run build_runner build --delete-conflicting-outputs
          for BINARY in $BINS; do \
            dart compile exe ${CROSS} bin/${BINARY}.dart -v -o sshnp/${BINARY}${EXT};
          done
      - name: Build admin API
        working-directory: ./apps/admin/admin_api
        run: |
          dart pub get --enforce-lockfile
          dart compile exe ${CROSS} bin/np_admin.dart -v -o ../../../packages/dart/sshnoports/sshnp/np_admin${EXT}
      - name: Compile debug binaries (Non-Windows)
        if: ${{ matrix.platform != 'windows' }}
        run: |
          dart compile exe ${CROSS} bin/srvd.dart -v -o sshnp/srvd
          dart compile exe ${CROSS} bin/srvd.dart -D ENABLE_SNOOP=true -v -o sshnp/debug/srvd
      - name: Generate man pages and CHANGELOG (Linux only)
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update && sudo apt-get install -y help2man
          # Conditionally install the cross-libraries based on arch
          case "${{ matrix.arch }}" in
            riscv64)
              sudo apt-get install -y libc6-riscv64-cross
              export QEMU_LD_PREFIX="/usr/riscv64-linux-gnu"
              ;;
            arm7)
              sudo apt-get install -y libc6-armhf-cross
              export QEMU_LD_PREFIX="/usr/arm-linux-gnueabihf"
              # Arm7 needs more persuading to run in Qemu
              sudo ln -s /usr/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3 /lib/ld-linux-armhf.so.3
              export LD_LIBRARY_PATH="/usr/arm-linux-gnueabihf/lib:/usr/arm-linux-gnueabihf/lib/arm-linux-gnueabihf"
              ;;
            *)
              ;;
          esac
          DBINS="${BINS} np_admin srvd"
          for BINARY in ${DBINS}; do \
            help2man -N --no-discard-stderr sshnp/${BINARY} -o sshnp/${BINARY}.1;
            gzip -n9 sshnp/${BINARY}.1;
          done
          cp CHANGELOG.md sshnp/
          gzip -n9 sshnp/CHANGELOG.md
      - name: Install nfpm and create packages (Linux only)
        if: ${{ matrix.platform == 'linux' }}
        run: |
          go install github.com/goreleaser/nfpm/v2/cmd/nfpm@be6fd83eed6f241359ae3e7d340a13f197ae6463
          nfpm -v
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d > ./gpg.key
          nfpm pkg --packager deb -t tarball
          nfpm pkg --packager rpm -t tarball
      - name: Build Windows Services (Windows only)
        if: ${{ matrix.platform == 'windows' }}
        working-directory: ./packages/csharp/WindowsBinaryService
        run: |
          dotnet publish --configuration Release -p:DefineConstants="SSHNPD"
          mv bin/Release/net*/win-x64/publish/WindowsBinaryService.exe ../../dart/sshnoports/sshnp/sshnpdService.exe
      - name: Codesign Windows Binaries (Windows only)
        if: ${{ matrix.platform == 'windows' }}
        working-directory: ./packages/dart/sshnoports/sshnp
        env:
          WINDOWS_SIGNTOOL_ARGS: ${{ secrets.WINDOWS_SIGNTOOL_ARGS }}
          WINDOWS_SIGNTOOL_PATH: ${{ secrets.WINDOWS_SIGNTOOL_PATH }}
        run: |
          source ../../../../tools/codesign_windows.sh
          for BINARY in $BINS; do \
            sign_file "$BINARY.exe";
          done
          sign_file "sshnpdService.exe"
      - name: Build and Sign Windows Installer (Windows only)
        if: ${{ matrix.platform == 'windows' }}
        working-directory: ./tools/windows-msi
        env:
          WINDOWS_SIGNTOOL_ARGS: ${{ secrets.WINDOWS_SIGNTOOL_ARGS }}
          WINDOWS_SIGNTOOL_PATH: ${{ secrets.WINDOWS_SIGNTOOL_PATH }}
        run: |
          dotnet tool install --global wix --version 6.0.2
          wix extension add -g WixToolset.Util.wixext/6.0.2
          wix extension add -g WixToolset.UI.wixext/6.0.2
          mkdir bin
          cp ../../packages/dart/sshnoports/sshnp/{sshnpd,at_activate,sshnp,npp,npp_atserver,npp_file,npt,srv,sshnpdService}.exe ./bin/
          cp ../../packages/dart/sshnoports/bundles/core/config/sshnpd.yaml ./bin/
          wix build -ext WixToolset.Util.wixext -ext WixToolset.UI.wixext \
              -arch x64 -o build/NoPorts.msi noports.wxs
          # Sign the generated MSI
          source ../codesign_windows.sh
          sign_file "build/NoPorts.msi"
          cp build/NoPorts.msi ../../packages/dart/sshnoports/tarball/NoPorts-${VERSION}-x64.msi
          cp build/NoPorts.msi ../../packages/dart/sshnoports/tarball/NoPorts-x64.msi
      - name: Copy additional bundle items to build
        run: |
          cp -r bundles/core/* sshnp/
          cp -r bundles/${{ matrix.bundle }}/* sshnp/
          cp LICENSE sshnp
      - name: Codesign MacOS Bundle (MacOS only)
        if: ${{ matrix.platform == 'macos' }}
        env:
          MACOS_CODESIGN_CERT: ${{ secrets.MACOS_CODESIGN_CERT }}
          MACOS_CODESIGN_CERT_PASSWORD:
            ${{ secrets.MACOS_CODESIGN_CERT_PASSWORD }}
          MACOS_SIGNING_IDENTITY: ${{ secrets.MACOS_SIGNING_IDENTITY }}
          MACOS_KEYCHAIN_PASSWORD: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
        run: |
          # Load certificate
          CERT_PATH=$RUNNER_TEMP/noports-codesign.p12
          echo -n "$MACOS_CODESIGN_CERT" | base64 --decode -o $CERT_PATH
          # create temp keychain
          KEYCHAIN_PATH=$RUNNER_TEMP/build.keychain
          security create-keychain -p "$MACOS_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security default-keychain -s $KEYCHAIN_PATH
          security unlock-keychain -p "$MACOS_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security import $CERT_PATH -k $KEYCHAIN_PATH -P "$MACOS_CODESIGN_CERT_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:apple,:,codesign: -s -k "$MACOS_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          # codesign
          DBINS="debug/srvd ${BINS} np_admin srvd"
          for BINARY in ${DBINS}; do \
            /usr/bin/codesign \
              --force \
              -s "$MACOS_SIGNING_IDENTITY" \
              --options=runtime \
              --entitlements ./tools/templates/entitlements.plist \
              --prefix "com.atsign." \
              --timestamp \
              -v \
              sshnp/${BINARY};
          done
      - name: Compress to zip (MacOS only)
        if: ${{ matrix.platform == 'macos' }}
        run:
          ditto -c -k --keepParent sshnp tarball/${{ matrix.output-name }}.zip
      - name: Compress to tgz (Linux only)
        if: ${{ matrix.platform == 'linux' }}
        run: tar -cvzf tarball/${{ matrix.output-name }}.tgz sshnp
      - name: Compress to zip (Windows only)
        if: ${{ matrix.platform == 'windows' }}
        run:
          powershell -c 'Compress-Archive -Path sshnp -Destination tarball/${{ matrix.output-name }}.zip'
      - name: Notarize the build (MacOS only)
        if: ${{ matrix.platform == 'macos' }}
        env:
          MACOS_APPLE_ID: ${{ secrets.MACOS_APPLE_ID }}
          MACOS_TEAM_ID: ${{ secrets.MACOS_TEAM_ID }}
          MACOS_APPLE_ID_PASSWORD: ${{ secrets.MACOS_APPLE_ID_PASSWORD }}
        run: |
          xcrun notarytool submit tarball/${{ matrix.output-name }}.zip \
            --apple-id "$MACOS_APPLE_ID" \
            --team-id "$MACOS_TEAM_ID" \
            --password "$MACOS_APPLE_ID_PASSWORD" \
            --wait
      - name: Upload the build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name:
            ${{ matrix.output-name
            }}-${{github.ref_name}}-${{github.run_number}}-${{github.run_attempt}}
          path: ./packages/dart/sshnoports/tarball
          if-no-files-found: error

  web_build:
    needs: verify_tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout multibuild branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: multibuild-${{github.run_number}}
      - name: Setup node-version
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '24.2.0'
      - name: Build admin webapp
        working-directory: ./apps/admin/webapp
        run: |
          mkdir -p sshnp/web/admin
          mkdir tarball
          npm ci
          npm run build
          cp -r dist/* sshnp/web/admin/
          tar -cvzf tarball/sshnp-web-admin-noarch.tgz sshnp
      - name: Upload the build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name:
            sshnp-web-admin-noarch-${{github.ref_name}}-${{github.run_number
            }}-${{github.run_attempt}}
          path: ./apps/admin/webapp/tarball
          if-no-files-found: error

  universal_sh:
    if: startsWith(github.ref, 'refs/tags/v')
    defaults:
      run:
        working-directory: ./packages/dart/sshnoports/bundles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: |
          write_metadata() {
            start_line="# SCRIPT METADATA"
            end_line="# END METADATA"
            file=$1
            variable=$2
            value=$3
            # since this is linux only, sed -i is safe without a file ext.
            sed -i "/$start_line/,/$end_line/s|$variable=\".*\"|$variable=\"$value\"|g" "$file"
          }
          REF=${{ github.ref }}
          TAG=${REF:11}
          write_metadata universal.sh sshnp_version "$TAG"
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: universal.sh-${{github.ref_name}}-${{github.run_number}}-${{github.run_attempt}}
          path: ./packages/dart/sshnoports/bundles/universal.sh
          if-no-files-found: error

  github-release:
    name: >-
      Upload artifacts and generate SBOMs and checksums for provenance
    needs: [main_build, web_build, universal_sh]
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    permissions:
      contents: write # Mandatory for making GitHub Releases
      id-token: write # Mandatory for sigstore
      attestations: write
    steps:
      - name: Checkout pubspec.lock
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          sparse-checkout: packages/dart/sshnoports/pubspec.lock
          sparse-checkout-cone-mode: false
      - name: Download all the tarballs
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: tarballs/
      - name: Generate SBOM
        uses: sbomify/github-action@ac8b0d423c90447f3011ef8ab5f9ff2e854c6931 # v26.2.0
        env:
          TOKEN: ${{ secrets.SBOMIFY_TOKEN }}
          COMPONENT_ID: '-93khk8pUi'
          LOCK_FILE: './packages/dart/sshnoports/pubspec.lock'
          COMPONENT_VERSION: ${{github.ref_name}}-gha${{github.run_number}}
          OUTPUT_FILE: 'tarballs/noports_dart-${{github.ref_name}}-sbom.cdx.json'
          AUGMENT: true
          ENRICH: true
          UPLOAD: true
      - name: Move packages for signing
        run: |
          cd tarballs
          mv */*.deb .
          mv */*.msi .
          mv */*.rpm .
          mv */*.sh .
          mv */*.tgz .
          mv */*.zip .
          rm -Rf -- */
      - name: Generate SHA256 checksums
        working-directory: tarballs
        run: sha256sum * > checksums.txt
      - name: Upload artifacts to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        # Upload to GitHub Release using the `gh` CLI.
        # `tarballs/` contains the built packages, and the
        # sbomify produced SBOMs
        run: >-
          gh release upload '${{ github.ref_name }}' tarballs/** --repo '${{
          github.repository }}'
      - id: hash
        name: Pass artifact hashes for SLSA provenance
        working-directory: tarballs
        run: |
          echo "hashes=$(cat checksums.txt | base64 -w0)" >> "$GITHUB_OUTPUT"
      - name: GitHub attestation
        uses: actions/attest@a1948c3f048ba23858d222213b7c278aabede763 # v4.1.1
        with:
          subject-path: "tarballs/**"

  provenance:
    needs: [github-release]
    permissions:
      actions: read # Needed for detection of GitHub Actions environment.
      id-token: write # Needed for provenance signing and ID
      contents: write # Needed for release uploads
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0 # 5a775b367a56d5bd118a224a811bba288150a563
    with:
      base64-subjects: "${{ needs.github-release.outputs.hashes }}"
      upload-assets: true

  cleanup:
    name: Clean up temporary branch
    needs: [main_build]
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to delete workflow branch
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: multibuild-${{github.run_number}}
      - name: Delete workflow branch
        run: git push origin --delete multibuild-${{github.run_number}}

  notify_on_completion:
    needs: [github-release, cleanup]
    runs-on: ubuntu-latest
    steps:
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@04e7733ead0e8a31a502adb271aadbc7f8d496d9 # v2
        with:
          name:
            SSH no ports binaries were built by GitHub Action ${{
            github.run_number }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}

  notify_on_failure:
    if: failure()
    needs: [github-release, cleanup]
    runs-on: ubuntu-latest
    steps:
      - name: Google Chat Notification
        uses: atsign-company/google-chat-notification@69f3920c9c9372c296112b25eaea0bddab9ee115 # v2.0.1
        with:
          name:
            SSH no ports binaries build by GitHub Action ${{ github.run_number
            }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
