name: NoPorts Desktop Release

on:
  push:
    tags:
      - 'desktop*.*.*\+*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify_tags:
    permissions:
      contents: write # Needed to create workflow branch
    runs-on: ubuntu-latest
    outputs:
      bundle_id: ${{ steps.metadata.outputs.bundle_id }}
      asset_name: ${{ steps.metadata.outputs.asset_name }}
      sbom_name: ${{ steps.metadata.outputs.sbom_name }}
    steps:
      - name: Checkout target branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Create action branch
        run: |
          git config --global user.name 'Atsign Robot'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git checkout -b npt-release-${{github.run_number}}
      - name: Update pubspec.yaml version if tag
        shell: bash
        if: github.ref_type == 'tag'
        working-directory: packages/dart/npt_flutter
        run: |
          REF=${{ github.ref_name }}
          # tag is desktop1.2.3+4, we want 1.2.3+4
          VER=${REF#desktop}
          sed -i "0,/version:/{s/version: \(.*\)/version: ${VER}/}" pubspec.yaml
          if [ "$(git status --porcelain)" ]; then
            git add .
            git commit -m 'ci: Updated version to tag'
          fi
      - name: Push changes to branch
        run: git push --set-upstream origin npt-release-${{github.run_number}}
      - name: Derive bundle metadata
        id: metadata
        shell: bash
        run: |
          # BUNDLE_ID is used to uniquely identify the build artifact.
          # If it's a tag build, use the tag name as the bundle ID
          # Otherwise, use the short SHA of the commit
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            BUNDLE_ID="${GITHUB_REF_NAME}"
          else
            BUNDLE_ID="${GITHUB_SHA::7}"
          fi
          echo "bundle_id=${BUNDLE_ID}" >> "$GITHUB_OUTPUT"
          echo "asset_name=NoPortsDesktop-${BUNDLE_ID}-windows-x64.zip" >> "$GITHUB_OUTPUT"
          echo "sbom_name=NoPortsDesktop-${BUNDLE_ID}-sbom.cdx.json" >> "$GITHUB_OUTPUT"

  generate-sbom:
    needs: verify_tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: npt-release-${{github.run_number}}
      - name: Generate SBOM
        uses: sbomify/github-action@ac8b0d423c90447f3011ef8ab5f9ff2e854c6931 # v26.2.0
        env:
          TOKEN: ${{ secrets.SBOMIFY_TOKEN }}
          COMPONENT_ID: 'xUUCaZd4OWr1'
          LOCK_FILE: 'packages/dart/npt_flutter/pubspec.lock'
          COMPONENT_VERSION: ${{ needs.verify_tags.outputs.bundle_id }}-gha${{github.run_number}}
          OUTPUT_FILE: 'packages/dart/npt_flutter/${{ needs.verify_tags.outputs.sbom_name }}'
          AUGMENT: true
          ENRICH: true
          UPLOAD: true
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sbom
          path: packages/dart/npt_flutter/${{ needs.verify_tags.outputs.sbom_name }}

  build-windows-desktop:
    needs: [verify_tags, generate-sbom]
    runs-on: windows-signer # codesign_windows.sh only works in windows-signer runner
    permissions:
      contents: write # Needed for release uploads
      id-token: write # For attestation OIDC token
      attestations: write # To persist attestation
      artifact-metadata: write # To create artifact storage record
    outputs:
      hashes: ${{ steps.release.outputs.hashes }}
    steps:
      - name: Checkout action branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: npt-release-${{github.run_number}}

      - name: Download SBOM
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: sbom
          path: packages/dart/npt_flutter

      # upon installing flutter in this windows-signer,
      # subsequent steps will need to use `shell: bash`
      - name: Install Flutter stable
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: stable
          cache: false

      - name: Build and Sign Windows desktop binaries
        shell: bash # this line is needed because we are in a windows-signer
        working-directory: packages/dart/npt_flutter
        env:
          WINDOWS_SIGNTOOL_ARGS: ${{ secrets.WINDOWS_SIGNTOOL_ARGS }}
          WINDOWS_SIGNTOOL_PATH: ${{ secrets.WINDOWS_SIGNTOOL_PATH }}
        run: |
          flutter pub get
          printf "API_KEY=''\n" > .env # Create a blank .env to avoid build error
          flutter build windows --release
          source "${GITHUB_WORKSPACE}/tools/codesign_windows.sh"
          shopt -s nullglob
          for FILE in build/windows/x64/runner/Release/*.exe \
                      build/windows/x64/runner/Release/*.dll; do
            sign_file "$FILE"
          done

      - name: Package using powershell
        working-directory: packages/dart/npt_flutter
        shell: powershell
        env:
          ASSET_NAME: ${{ needs.verify_tags.outputs.asset_name }} # e.g. "NoPortsDesktop-abc1234-windows-x64.zip"
        run: |
          # if the asset already exists, 
          # remove it first to avoid Compress-Archive error
          if (Test-Path $env:ASSET_NAME) {
            Remove-Item $env:ASSET_NAME -Force
          }
          # everything in the Release/ dir should be already signed
          # let's put all of those things into zip file
          Compress-Archive `
            -Path build/windows/x64/runner/Release/* `
            -DestinationPath $env:ASSET_NAME

      - name: Upload workflow artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: npt_flutter_${{ needs.verify_tags.outputs.bundle_id }}_${{ github.run_number }}_${{ github.run_attempt }}
          path: packages/dart/npt_flutter/${{ needs.verify_tags.outputs.asset_name }}
          if-no-files-found: error

      - name: If tag push, upload desktop bundle to GitHub release
        id: release
        if: github.ref_type == 'tag'
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ github.ref_name }}
          ASSET_NAME: ${{ needs.verify_tags.outputs.asset_name }}
          SBOM_NAME: ${{ needs.verify_tags.outputs.sbom_name }}
        working-directory: packages/dart/npt_flutter
        shell: bash
        run: |
          echo "Generating SHA for ${ASSET_NAME}"
          sha256sum "${ASSET_NAME}" > checksums.txt
          cat checksums.txt
          echo "Generating SHA for ${SBOM_NAME}"
          sha256sum "${SBOM_NAME}" >> checksums.txt
          cat checksums.txt
          echo "hashes=$(cat checksums.txt | base64 -w0)" >> "$GITHUB_OUTPUT"
          # Check if release exists, create as draft if it doesn't
          if ! gh release view "${RELEASE_TAG}" >/dev/null; then
            echo "Release ${RELEASE_TAG} not found. Creating a draft release..."
            gh release create "${RELEASE_TAG}" --draft --title "${RELEASE_TAG}" --notes "Automated release for ${RELEASE_TAG}"
          fi
          gh release upload \
            "${RELEASE_TAG}" \
            "${ASSET_NAME}" \
            "${SBOM_NAME}" \
            checksums.txt \
            --clobber

      - name: GitHub attestation
        uses: actions/attest@a1948c3f048ba23858d222213b7c278aabede763 # v4.1.1
        with:
          subject-path: "packages/dart/npt_flutter/${{ needs.verify_tags.outputs.asset_name }}"
          sbom-path: "packages/dart/npt_flutter/${{ needs.verify_tags.outputs.sbom_name }}"

  provenance:
    if: github.ref_type == 'tag'
    needs: [build-windows-desktop]
    permissions:
      actions: read # Needed for detection of GitHub Actions environment.
      id-token: write # Needed for provenance signing and ID
      contents: write # Needed for release uploads
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0 # 5a775b367a56d5bd118a224a811bba288150a563
    with:
      base64-subjects: "${{ needs.build-windows-desktop.outputs.hashes }}"
      upload-assets: true

  cleanup:
    name: Clean up temporary branch
    needs: [build-windows-desktop]
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to delete workflow branch
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Delete workflow branch
        run: git push origin --delete npt-release-${{github.run_number}}
