name: npt_flutter

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - trunk

    paths:
      - ".github/workflows/npt_flutter_tests.yaml"
      - "packages/dart/npt_flutter/**"

  pull_request:
    branches:
      - trunk
    paths:
      - ".github/workflows/npt_flutter_tests.yaml"
      - "packages/dart/npt_flutter/**"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: "stable"
          flutter-version: "3.41.9"
      - name: flutter pub get
        working-directory: packages/dart/npt_flutter
        run: flutter pub get
      - name: Create .env file for tests
        working-directory: packages/dart/npt_flutter
        run: touch .env
      - name: Run build runner
        working-directory: packages/dart/npt_flutter
        run: dart run build_runner build --delete-conflicting-outputs
      - name: flutter analyze
        working-directory: packages/dart/npt_flutter
        run: flutter analyze --no-fatal-warnings --no-fatal-infos
      - name: flutter test --exclude-tags=integration
        working-directory: packages/dart/npt_flutter
        run: flutter test --exclude-tags=integration
      - name: Run osv-scanner
        uses: google/osv-scanner-action/osv-scanner-action@9a498708959aeaef5ef730655706c5a1df1edbc2 # v2.3.8
        with:
          scan-args: |-
            --lockfile=./packages/dart/npt_flutter/pubspec.lock
