name: Windows Signer Keepalive
# Workflow to regularly exercise windows-signer self hosted runner to avoid
# time out after two weeks

on:
  schedule:
    # 0654 each Monday
    - cron: '54 6 * * 1'
  workflow_dispatch:

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  run-script:
    runs-on: windows-signer
    
    steps:
      - name: Run trivial script
        run: |
          echo "Windows Signer Keepalive"
