name: end2end_tests

on:
  workflow_dispatch:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  end2end_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f # v1.5.0
        with:
          sdk: stable

      # Install dependencies in sshnoports
      - name: Install dependencies in sshnoports
        working-directory: .
        run: dart pub get

      # Install dependencies in end2end_tests
      - name: Install dependencies in test/end2end_tests
        working-directory: test/end2end_tests
        run: dart pub get

      - name: Run end2end_tests
        working-directory: test/end2end_tests
        run: dart run test.dart
