name: unit_tests

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - trunk

  pull_request:
    branches:
      - trunk
      - release-v*.*.*

jobs:
  cli_tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/composite/verify_cli_tags
  np_admin-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dart-lang/setup-dart@7654d458321ee25acccccfdb86cd48bd95768ff1 # v1.8.0
        with:
          sdk: stable
      - name: dart pub get enforce lockfile
        working-directory: apps/admin/admin_api
        run: dart pub get --enforce-lockfile
      - name: dart analyze
        working-directory: apps/admin/admin_api
        run: dart analyze
      - name: dart test
        working-directory: apps/admin/admin_api
        run: dart test
      # Runs osv-scanner to find any vulnerable Dart dependencies
      # It needs to look at pubspec.lock files, which is why it's
      # placed here, as the `dart pub get` above will create them
      - name: Run osv-scanner
        uses: google/osv-scanner-action/osv-scanner-action@9a498708959aeaef5ef730655706c5a1df1edbc2 # v2.3.8
        with:
          scan-args: |-
            --lockfile=./apps/admin/admin_api/pubspec.lock

  sshnoports-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dart-lang/setup-dart@7654d458321ee25acccccfdb86cd48bd95768ff1 # v1.8.0
        with:
          sdk: stable
      - name: dart pub get enforce lockfile
        working-directory: packages/dart/sshnoports
        run: dart pub get --enforce-lockfile
      - name: dart analyze
        working-directory: packages/dart/sshnoports
        run: dart analyze
      - name: dart test
        working-directory: packages/dart/sshnoports
        run: dart test
      # Runs osv-scanner to find any vulnerable Dart dependencies
      # It needs to look at pubspec.lock files, which is why it's
      # placed here, as the `dart pub get` above will create them
      - name: Run osv-scanner
        uses: google/osv-scanner-action/osv-scanner-action@9a498708959aeaef5ef730655706c5a1df1edbc2 # v2.3.8
        with:
          scan-args: |-
            --lockfile=./packages/dart/sshnoports/pubspec.lock

  noports_core-unit_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dart-channel: [stable,beta]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dart-lang/setup-dart@7654d458321ee25acccccfdb86cd48bd95768ff1 # v1.8.0
        with:
          sdk: ${{ matrix.dart-channel}}
      - name: dart pub get
        working-directory: packages/dart/noports_core
        run: dart pub get
      - name: dart run build_runner build
        working-directory: packages/dart/noports_core
        run: dart run build_runner build
      - name: dart analyze
        working-directory: packages/dart/noports_core
        run: dart analyze
      - name: dart test
        working-directory: packages/dart/noports_core
        run: dart test
      # Runs osv-scanner to find any vulnerable Dart dependencies
      # It needs to look at pubspec.lock files, which is why it's
      # placed here, as the `dart pub get` above will create them
      - name: Run osv-scanner
        uses: google/osv-scanner-action/osv-scanner-action@9a498708959aeaef5ef730655706c5a1df1edbc2 # v2.3.8
        with:
          scan-args: |-
            --lockfile=./packages/dart/noports_core/pubspec.lock
